[login]
//usuario=sim
usuariopadrao=tecsoft
senhapadrao=filosofia

#senhapadrao=alpinismo
#senhapadrao=novasenha

#filialbase=8
#host=rot.calcadospetipe.com.br
#banco=teste

#filialbase=2
#porta=5432
#host=177.135.65.248
#banco=teste

filialbase=4
host=10.16.1.1
#host=santaapolonia.no-ip.org
#banco=tecsoft
banco=apolonia
#banco=bmh
#banco=apolonia
#host=10.16.1.1
#banco=maxvida
#banco=nazare
#anco=gama
#banco=primelub
#banco=zitadebug
#banco=proclean
#banco=mediatools
#anco=proclean
#banco=petipe
#banco=andra
#banco=mariah_sa
porta=5434
;banco=teste_grade
;porta=5434
#banco=tecsoft
;banco=maxvida
#banco=tecsoft
#banco=primelub
#banco=mediatools
#banco=proclean
#banco=nazare
#banco=mariah_sa
#banco=zitasa2015

#Apolonia
#banco=tecsoft
#host=santaapolonia.no-ip.org

#mediatools
#banco=teste
#host=177.135.65.248

#BcProdutos
#host=54.207.92.17
#banco=bcprodutos


LogHabilitado=0
LogEcf=0

#banco=tecsoft
#host=177.19.235.217
#banco=gama
#banco=merkante
#banco=frettalaguna
#host=186.215.116.35
#banco=tecsoft
banco=infotec
#banco=treinamento
#porta=5434
#anco=tecsoft
#banco=teste_grade
#banco=tecsoft
#banco=treinamento
#banco=andra
#banco=teste
#banco=proclean
#banco=andra
#banco=tecsoft
#banco=proclean
#banco=edsonmotos

host=localhost
#banco=andra
#host=179.184.95.30
#host=localhost
#banco=tecsoft
#banco=edsonmotos
#banco=edsonmotos
#anco=tecsoft
;banco=apolonia
#banco=zitasa2015
#host=localhost
#host=10.16.1.1

##host=177.19.235.217


#banco=tecsoft
#host=179.184.95.30
#banco=treinamento
#host=rot.calcadospetipe.com.br
#banco=tecsoft
#anco=mediatools
#porta=5434
#porta=1433
#banco=mediatools
#banco=krah_ice
#banco=mediatools
#banco=petipe
#banco=kilar
#banco=apolonia
#banco=proclean
#banco=proclean2
#banco=tecsoft
#banco=korpora
#banco=media
#anco=tecsoft
#banco=macrolar
#banco=frettalaguna
#banco=tecsoft
#banco=agro
#banco=brognoli
#banco=proclean
#banco=andra
#banco=newbelle
#banco=exclusiva_ceçççntro
#banco=infotec


#banco=andra
#anco=proclean
#banco=gama
#banco=ponte
#banco=mediatools
#banco=zitasa2015
#banco=ceplucio
#banco=zita
#banco=fretta_2015
#banco=gamae
#banco=frettalaguna
#banco=mediatools
#banco=gamae
#banco=frettalaguna

#banco=nazare
#banco=proclean
#banco=tecsoft
#banco=petipe
#banco=proclean
#banco=agro
#banco=agro
#banco=agro
#banco=fretta_ecf2
#banco=tecsoft
#banco=gama
#host=177.19.235.217
#banco=gamae
#banco=gama
#banco=andra
#banco=mercadodooleo
#banco=avisa_beta
#banco=gamaeO
#anco=agro
#banco=mediatools
#anco=apolonia
#host=10.16.1.1

#banco=testezita
#host=186.215.116.35

#banco=tecsoft
#host=eletrofretta.dyndns.org
#banco=tecsoft


#Proclean
#host=proclean.no-ip.org

#banco=tecsoft
#host=rot.calcadospetipe.com.br

#banco=construtora
#host=186.215.116.35

#kilar
#banco=tecsoft
#host=187.94.97.6

#banco=
#host=186.215.116.35

#banco=rita
#host=localhost

#banco=tecsoft
#host=187.55.211.38

#banco=infotec2
#host=10.16.1.96

#infotec
;banco=tecsoft
#ost=186.215.116.178

#banco=tecsoftold
#host=200.175.61.147

#banco=tecsoft
#host=eletrofretta.dyndns.org

#banco=gama
#host=localhos

     
#banco=testenfe
#host=186.215.116.178

#apolonia
#banco=treinamento
#banco=tecsoft
#host=177.19.235.217

#eletro delta
#banco=tecsoft
#host=187.55.208.102

#host=rot.frettalar.com.br
#banco=tecsoft

#host=localhost
#porta=5433
#banco=clamar_mtz

#banco=macromaq
#banco=tecsoft

#banco=gama

#banco=tecsoft
#host=rot.frettalar.com.br

#eletrodelta

#host=10.31.1.1
#eletro delta

#host=201.34.141.99
#host=201.34.141.99

#host=10.16.1.1
#banco=gama

#FRETTA CRICIUMA
#host=suportefretta.dyndns.info
#host=189.115.78.153
#host=200.180.4.80
#host=177.43.63.248
#banco=tecsoft

#banco=agro
#gama
#host=187.52.178.148

#host=189.31.66.218 holding

#VALDIR
#host=201.47.57.59


#zita agro
#banco=agro
#host=186.215.116.35

#kilar
#host=200.175.61.147
#banco=tecsoft
#host=200.146.120.227


MaxColAutenticadora=56

[modulos]
atual=

disponiveis=contasareceber,adminsistema,imoveis,estoque,caixa,cobranca,interlojas,entrega,montagens,imoveis,livrosfiscais,financeiro,sac,bancos,contabil,contaspagar,vendas
indisponiveis=adminsistema,vendas,estoque

[impressoraetiqueta]
impressora=PDFCreator
tipo=jato
[impressoras]
imprimircarneecf=0
imprimirlinefeednaimpressoramatricial=0
notafiscalservicos=
contrato=
carne=
boleto=
OSP=
SetupProcesso=
ControleProcesso=
fechamentocaixa=Generic / Text Only
notafiscal=

[frentecaixa]
#trabalharcomo=sim
imprimircarneecf=1
SetupProcesso=
ControleProcesso=
imprimirlinefeednaimpressoramatricial=1
boleto=Generic / Text Only
OSP=
notafiscalservicos=Generic / Text Only
notafiscal=PDFCreator
contrato=
fechamentocaixa=Generic / Text Only

[autenticacao]
autenticadora=1
autenticarecf=0

[PCP]
DirExp=
[SPED]
DirSpedFiscal=N:\lixo
DirSpedContabil=N:\Clientes\zita\SPED
DirSpedFCont=
DirEFDContribuições=N:\lixo
[EXPORTAÇÃO]
DirExportação=N:\Gedovar\clientes\zita
[EXPORTAÇÃO PRODUTOS]
DirExportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[EXPORTAÇÃO NOTAS TRANSFERENCIA]
DirExportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[IMPORTAÇÃO PRODUTOS]
DirImportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[IMPORTAÇÃO NOTAS TRANSFERENCIA]
DirImportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[MovimentacaoDiaria]
Movimentos=

[NFe]
Ambiente=1
TipoEmissao=1

#filial 1 Nazare
#DirEnvio=C:\Unimake\UniNFe\17324469000189\Envio
#DirRetorno=C:\Unimake\UniNFe\17324469000189\Retorno
#DirEnviados=C:\Unimake\UniNFe\17324469000189\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\17324469000189\Erro
#DirComp=c:\unimake\compartilha_nazare


#DirEnvio=c:\Unimake\UniNFe\82858903000172\Envio
#DirRetorno=c:\Unimake\UniNFe\82858903000172\Retorno
#DirEnviados=c:\Unimake\UniNFe\82858903000172\Enviado\Autorizados
#DirErros=c:\Unimake\UniNFe\82858903000172\Erro
#DirComp=c:\unimake\compartilha_apolonia


#DirEnvio=c:\Unimake\UniNFe\17324469000189\Envio
#DirRetorno=c:\Unimake\UniNFe\17324469000189\Retorno
#DirEnviados=c:\Unimake\UniNFe\17324469000189\Enviado\Autorizados
#DirErros=c:\Unimake\UniNFe\17324469000189\Erro
#DirComp=c:\unimake\compartilha_apolonia

#apolonia filial 6
#irEnvio=c:\Unimake\UniNFe\08362735000258\Envio
#irRetorno=c:\Unimake\UniNFe\08362735000258\Retorno
#irEnviados=c:\Unimake\UniNFe\08362735000258\Enviado\Autorizados
#irErros=c:\Unimake\UniNFe\08362735000258\Erro
#irComp=c:\unimake\compartilha_apolonia


#apolonia filial 7
;DirEnvio=c:\Unimake\UniNFe\82858903000504\Envio
;DirRetorno=c:\Unimake\UniNFe\82858903000504\Retorno
;DirEnviados=c:\Unimake\UniNFe\82858903000504\Enviado\Autorizados
;DirErros=c:\Unimake\UniNFe\82858903000504\Erro
;DirComp=c:\unimake\compartilha_apolonia

#apolonia filial 7
#DirEnvio=c:\Unimake\UniNFe\82858903000253\Envio
#DirRetorno=c:\Unimake\UniNFe\82858903000253\Retorno
#DirEnviados=c:\Unimake\UniNFe\82858903000253\Enviado\Autorizados
#DirErros=c:\Unimake\UniNFe\82858903000253\Erro
#DirComp=c:\unimake\compartilha_apolonia



#Andra
#DirEnvio=C:\Unimake\UniNFe\82514282000100\Envio
#DirRetorno=C:\Unimake\UniNFe\82514282000100\Retorno
#DirEnviados=C:\Unimake\UniNFe\82514282000100\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\82514282000100\Erro
#DirComp=C:\Unimake\UniNFe\82514282000100\compartilha

#Filial 6

#DirEnvio=C:\Unimake\UniNFe\08362735000258\Envio
#DirRetorno=C:\Unimake\UniNFe\08362735000258\Retorno
#DirEnviados=C:\Unimake\UniNFe\08362735000258\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\08362735000258\Erro
#DirComp=c:\unimake\compartilha_apolonia

#jlw
#DirEnvio=C:\Unimake\UniNFe\10431402000102\Envio
#DirRetorno=C:\Unimake\UniNFe\10431402000102\Retorno
#DirEnviados=C:\Unimake\UniNFe\10431402000102\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\10431402000102\Erro
#DirComp=C:\Unimake\UniNFe\10431402000102\Compartilha


#filial6 gama
#DirEnvio=C:\Unimake\UniNFe\06374677000176\Envio
#DirRetorno=C:\Unimake\UniNFe\06374677000176\Retorno
#DirEnviados=C:\Unimake\UniNFe\06374677000176\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\06374677000176\Erro
#DirComp=C:\Unimake\UniNFe\06374677000176\Compartilha

#filial6
DirEnvio=C:\Unimake\UniNFe\17324469000189\Envio
DirRetorno=C:\Unimake\UniNFe\17324469000189\Retorno
DirEnviados=C:\Unimake\UniNFe\17324469000189\Enviado\Autorizados
DirErros=C:\Unimake\UniNFe\17324469000189\Erro
DirComp=C:\Unimake\UniNFe\08362735000258\Compartilha

Visualizar=0
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
#ExecNFes=C:\Unimake\UniNFe\uninfe.exe
ExecDANFE=C:\Unimake\UniNFe\unidanfe.exe
NumVias=1
Logotipo=c:\liriomimoso.jpg
ModeloDANFE=C:\projetos.vcl\apps\tecsoft\Modelos Relatórios\DANFeNFCeA4.fr3

#[ecf]
#porta=4
#codigo=2
#velocidadeporta=115200
#Docto_NFE=33305
#Tipo_NFE=E
#Operacao_NFE=1
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
ExecNFe=C:\Unimake\UniNFe\uninfe.exe

[Outros]
percentualdescontoetiqueta=0,00
CaminhoArquivoImportacao=C:\Users\CPU\Desktop\lista.txt
CaminhoArquivoImportacaoInventario=C:\temp\coletor\temp.txt
[Exportacao]
DirVendas=C:\Users\CPU\Desktop
DirReducoes=C:\Users\CPU\Desktop
[Importacao]
Produtos=N:\Clientes\Clamar\PRODUTOS.TXT
Estoques=N:\Clientes\Clamar\ESTOQUE.TXT
Clientes=C:\projetos.vcl\apps\tecsoft\Anexo_X.txt

[ConsultaComnpras]
PedidosEntreFiliais=0
[impchq]
marca=TSP
tipoporta=Paralela
numeroporta=1
[NFSe]
DirEnvio=C:\Unimake\UniNFSe\10431402000102\nfse\Envio
DirRetorno=C:\Unimake\UniNFSe\10431402000102\nfse\Retorno
Ambiente=1
 
[Cobrança Bancária]
Diretorio=C:\lixo
[NFCe]
DataHoraInicialContingenciaNFCe=
RazaoContingenciaNFCe=TEMPO MÁXIMO DE ESPERA ESGOTADO
[Empresa_Desenvolvedora]
NomeEmpresaDesenvolvedora=4A4D50324D5154918726690FE7351A08B8DA1AB8A3B54998AD9182F25984D6F1A691935E
CNPJDesenvolvedora=313138666B4A487F10D474D47F1C
IEDesenvolvedora=30
IMDesenvolvedora=30
NomeComercialSistema=544750DA873B27
VersaoPAFECF=3033256464
CodigoMD5=30
LaudoPAFECF=30
NumeroCredenciamento=30
Endereco1=527775B0BC82341D396F06C924A7D2E070F9485D13BEE8620724A12B
Endereco2=466E7E0D1506B989242272B08BF2943A
Telefone=34393F6BB1AF72F1BEF3
Contato=4A4D50324D5154918726690F
DataLaudoPAFECF=32312367508C4F5D303B
[NFeEntrada]
DirNotasEntrada=C:\projetos.vcl\apps\tecsoft\XMLTemp
