[login]
filialbase=6
banco=tecsoft_atual
host=10.16.1.1
porta=5431
MaxColAutenticadora=48

[modulos]
atual=

disponiveis=adminsistema,estoque,caixa,cobranca,livrosfiscais,financeiro,sac,bancos,contabil,contaspagar,vendas,contasareceber

#indisponiveis=vendas,estoque,caixa,cobranca,interlojas,entrega,montagens,contaspagar,financeiro,sac,contabil,bancos,livrosfiscais,contasareceber

[impressoraetiqueta]
[impressoras]

*[frentecaixa]
*trabalharcomo=sim
imprimircarneecf=0
SetupProcesso=
ControleProcesso=
imprimirlinefeednaimpressoramatricial=1
notafiscal=
contrato=
carne=
boleto=
fechamentocaixa=
OSP=
notafiscalservicos=PDFCreator

[autenticacao]
autenticadora=1
autenticarecf=0
*[ecf]
*marca=Bematech
*controle=34363C624E450C83E819DA5198;0002;1
_#vd=32393B68433D
_data=26/06/2007
_vd=32313867488B75

*[ecf]
*marca=Bematech
*controle=34363C624E450C83E819DA5198;0002;1
[PCP]
DirExp=
[SPED]
DirSpedFiscal=N:\Clientes\Clamar
DirSpedContabil=N:\Clientes\zita
DirSpedFCont=
DirEFDContribuições=
[EXPORTAÇÃO]
DirExportação=N:\Gedovar\clientes\zita
[EXPORTAÇÃO PRODUTOS]
DirExportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[EXPORTAÇÃO NOTAS TRANSFERENCIA]
DirExportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[IMPORTAÇÃO PRODUTOS]
DirImportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[IMPORTAÇÃO NOTAS TRANSFERENCIA]
DirImportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[MovimentacaoDiaria]
Movimentos=

[NFe]
Ambiente=2
TipoEmissao=1
DirEnvio=C:\Unimake\UniNFe\79863213000105\Envio
DirRetorno=C:\Unimake\UniNFe\79863213000105\Retorno
DirEnviados=C:\Unimake\UniNFe\79863213000105\Enviado\Autorizados
DirErros=C:\Unimake\UniNFe\79863213000105\Erro

#DirEnvio=C:\Unimake\UniNFe\82858903000172\Envio
#DirRetorno=C:\Unimake\UniNFe\82858903000172\Retorno
#DirEnviados=C:\Unimake\UniNFe\82858903000172\Enviado\Autorizados
#DirErros=C:\Unimake\UniNFe\82858903000172\Erro


DirComp=N:\Clientes\Apolonia\PendenciasNFe
Visualizar=1
ExecNFe=C:\Unimake\UniNFe\uninfe.exe
ExecDANFE=C:\Unimake\UniNFe\unidanfe.exe
NumVias=1
Logotipo=N:\imagens\gama1.jpg

#[ecf]
#porta=3
#codigo=9
Docto_NFE=18975
Tipo_NFE=E
Operacao_NFE=1
[Outros]
percentualdescontoetiqueta=0,00
[Exportacao]
DirVendas=C:\Users\CPU\Desktop
DirReducoes=C:\Users\CPU\Desktop
[Importacao]
Produtos=N:\Clientes\Clamar\PRODUTOS.TXT
Estoques=N:\Clientes\Clamar\ESTOQUE.TXT
Clientes=C:\projetos.vcl\apps\tecsoft\Anexo_X.txt
