[login]
#usuario=sim
usuariopadrao=tecsoft
senhapadrao=filosofia

#lite
filialbase=1
host=52.67.166.19
porta=5433
banco=ceron



#gama
filialbase=1
banco=tecsoft
host=186.249.192.135
porta=5432

#filialbase=6
filialbase=1
#banco=tecsoft
#banco=teste
#banco=usaconforto
#porta=5432
#host=localhost
host=10.16.1.1
#banco=ortobig
#banco=usaconforto
#banco=papellotti
#banco=macrolar
#banco=ceronteste
#banco=ceronteste
#banco=atrevida
#banco=puxare
#banco=ceron
#banco=papellotti
#banco=orthoshops18
banco=infotec2
#banco=agro90b
#banco=apolonia
#banco=gama
#banco=infotec
#banco=tecsoft_atual
#banco=wdcompensados
porta=5434

host=mediatools.ddns.net
filialbase=2
porta=5432
banco=tecsoft



#Petipe
filialbase=6
#host=186.215.191.174
host=186.225.255.4
#host=rot.calcadospetipe.com.br
banco=tecsoft
porta=5432


filialbase=14
host=santaapolonia.no-ip.org
banco=tecsoft
porta=5432



#puxare
filialbase=1
host=189.4.65.91
banco=tecsoft
porta=5432



#ortobig
host=ortobig.ddns.net
filialbase=1
banco=tecsoft
porta=5432



#Andra
filialbase=1
host=andrauniformes.ddns.net
banco=tecsoft
porta=5432

filialbase=1
porta=5434
host=10.16.1.1
banco=orthoshops










#infotec
filialbase=1
banco=tecsoft
host=170.84.16.2
porta=5432

filialbase=3
host=santaapolonia.no-ip.org
banco=tecsoft
porta=5432

#atrevida
filialbase=1
#host=52.67.166.19
#host=usaconforto.ddns.net
host=usaconforto1.ddns.net
#host=clickatrevida.ddns.net
banco=tecsoft
porta=5432

host=localhost
banco=beaba
porta=5432







filialbase=7
host=santaapolonia.no-ip.org
#banco=tecsoft
banco=tecsoft
#banco=teste
#banco=usaconforto
porta=5432













#usuariopadrao=vendas
#senhapadrao=1234





















































filialbase=1
banco=tecsoft
host=santaapolonia.no-ip.org
porta=5432


#GeorgiaBaby
filialbase=1
host=177.67.203.230
banco=tecsoft
porta=5432








#senhapadrao=alpinismo
#senhapadrao=novasenha





filialbase=3
host=177.67.203.230
banco=tecsoft
porta=5432


#Clinica do Pés
filialbase=1
porta=5432
host=201.86.51.130
banco=wd

filialbase=1
banco=edsonmotos
host=10.16.1.1
porta=5434




































#BC Produtos
filialbase=1
banco=bcprodutos
porta=5432
host=54.207.92.17




filialbase=1
banco=tecsoft
host=186.249.192.135
#host=localhost
porta=5432






#filialbase=1
##rta=5432
#ost=177.135.65.248
#banco=teste


#Proclean
#host=proclean.no-ip.org


#proclean
#host=177.207.223.42
#banco=tecsoft
#filialbase=2
#porta=5432


#banco=puxare
#banco=wd
#banco=bambini
#banco=zitasa2015
#banco=puxare
#anco=gama
#banco=apolonia
#banco=tecsoft_atual



filialbase=1
banco=apolonia
host=10.16.1.1
#host=localhost
porta=5434



#Andra
filialbase=1
host=mercadolandia.ddns.net
banco=tecsoft
porta=5433


#Fretta
filialbase=1
host=eletrofretta.dynu.net
banco=tecsoft
porta=5432





#banco=comeventos

#GeorgiaBaby
#host=georgiababyitj.ddns-intelbras.com.br
#banco=tecsoft


#host=andrauniformes.ddns.net
#Proclean

#host=179.184.19.202
#banco=tecsof98
#ilialbase=1

#filialbase=1
#banco=tecsoft
#host=eletrofretta.dynu.net
#porta=5432






#bc produtos
#host=54.207.92.17

#gama
#host=186.249.192.135


#ost=186.215.191.174
#host=rot.calcadospetipe.com.br
#host=santaapolonia.no-ip.org
#host=andrauniformes.ddns.net
#ortobig

#media tools
#host=mediatools.ddns.net


#host=ortobig.ddns.net

#MaxColAutenticadora=48

#porta=5434
#porta=5432
#banco=georgiababy
#banco=bcprodutos
#banco=mercadolandia
#banco=infotec
#banco=puxare
#anco=infotec
#banco=agro
#banco=tecsoft
#banco=primelub
#banco=upmais
#banco=andra
#nco=papellotti
#banco=apolonia
#banco=puxare
#banco=maragna
#banco=apolonia
#banco=vitorino
#banco=apolonia
#banco=apolonia
#banco=tecsoft
#banco=tecsoft_old
#banco=infotec
#banco=zitasa2015
#banco=apolonia
#banco=agro
#banco=teste
#banco=regimenormal
#banco=upmais
#banco=tecsoft_site

#banco=wd
#banco=mediatools

#banco=georgiababy
#banco=tecsoft
#banco=proclean
#banco=bcprodutos
#banco=bambini
#banco=tecsoft
#banco=andra
#banco=zitasa2015
#banco=apolonia
#banco=tecsoft

#banco=proclean
#banco=andra
#banco=andra
#banco=tecsoft_atual

#banco=tecsoft
#porta=5432
#banco=teste
#banco=ortobig
;banco=georgiababy
#banco=georgiababy
#banco=figueirense
#banco=figueirense
#banco=bcprodutos
#banco=beco
#banco=mediatools
#banco=zitasa2015
#banco=proclean
#banco=ortobig
#banco=infotec
#banco=wagner
#banco=ortobig
#banco=beco
#banco=tecsoft
#banco=ortobig
#banco=beco_sintegra
#banco=ortobig
#banco=andra
#banco=infotec20180620
#banco=infotec
#banco=zitadebug
#host=54.207.92.17
#banco=beco
#banco=ortobig
#banco=tecsoft
#banco=infotec

#banco=beco1

##banco=newbelle
#banco=damesko_teste
#banco=proclean
#banco=beco
#banco=infotec
#banco=tecsoft
#banco=tecsoft
#banco=apolonia
#banco=bmh
#banco=apolonia
#banco=apolonia
#host=10.16.1.1
#banco=maxvida
#banco=nazare
#anco=gama
#banco=primelub
#anco=proclean
#banco=proclean
#banco=mediatools
#anco=proclean
#banco=petipe
#banco=andra
#banco=mariah_sa
#porta=5432
;banco=teste_grade
#porta=5434
#banco=tecsoft
;banco=maxvida
#banco=tecsoft
#banco=primelub
#banco=mediatools
#banco=proclean
#banco=nazare
#banco=mariah_sa



#mediatools
#banco=tecsoft
#host=177.135.65.248

#BcProdutos
#host=54.207.92.17
#banco=bcprodutos


LogHabilitado=0
LogEcf=0
LogMessageFrenteCaixa=0

#banco=tecsoft
#host=177.19.235.217
#banco=gama
#banco=merkante
#banco=frettalaguna


#host=186.215.191.174
#banco=zitasa2015

#banco=infotec
#banco=treinamento
#porta=5434
#anco=tecsoft
#banco=teste_grade
#banco=tecsoft
#banco=treinamento
#banco=andra
#banco=teste
#banco=proclean
#banco=andra
#banco=tecsoft
#banco=proclean
#banco=edsonmotos

#ost=localhost
#anco=andra


#host=localhost
#banco=tecsoft
#banco=edsonmotos
#banco=edsonmotos
#anco=tecsoft
;banco=apolonia
#banco=zitasa2015
#host=localhost
#host=10.16.1.1

##host=177.19.235.217


#banco=tecsoft
#host=179.184.95.30
#banco=treinamento
#host=rot.calcadospetipe.com.br
#banco=tecsoft
#anco=mediatools
#porta=5434
#porta=1433
#banco=mediatools
#banco=krah_ice
#banco=mediatools
#banco=petipe
#banco=kilar
#banco=apolonia
#banco=proclean
#banco=proclean2
#banco=tecsoft
#banco=korpora
#banco=media
#anco=tecsoft
#banco=macrolar
#banco=frettalaguna
#banco=tecsoft
#banco=agro
#banco=brognoli
#banco=proclean
#banco=andra
#banco=newbelle
#banco=exclusiva_ceçççntro
#banco=infotec


#banco=andra
#anco=proclean
#banco=gama
#banco=ponte
#banco=mediatools
#banco=zitasa2015
#banco=ceplucio
#banco=zita
#banco=fretta_2015
#banco=gamae
#banco=frettalaguna
#banco=mediatools
#banco=gamae
#banco=frettalaguna

#banco=nazare
#banco=proclean
#banco=tecsoft
#banco=petipe
#banco=proclean
#banco=agro
#banco=agro
#banco=agro
#banco=fretta_ecf2
#banco=tecsoft

#banco=gama
#host=177.19.235.217

#banco=gamae
#banco=gama
#banco=andra
#banco=mercadodooleo
#banco=avisa_beta
#banco=gamaeO
#anco=agro
#banco=mediatools
#anco=apolonia
#host=10.16.1.1

#banco=testezita
#zita
#host=186.215.116.35
#host=186.215.191.174
#banco=agro
#host=eletrofretta.dyndns.org
#banco=tecsoft



#banco=tecsoft
#host=rot.calcadospetipe.com.br

#banco=construtora
#host=186.215.116.35

#kilar
#banco=tecsoft
#host=187.94.97.6

#banco=
#host=186.215.116.35

#banco=rita
#host=localhost

#banco=tecsoft
#host=187.55.211.38

#banco=infotec2
#host=10.16.1.96


#host=186.215.116.178


#banco=tecsoftold
#host=200.175.61.147

#banco=tecsoft
#host=eletrofretta.dyndns.org

#banco=gama
#host=localhos

     
#banco=testenfe
#host=186.215.116.178

#apolonia
#banco=treinamento
#banco=tecsoft
#host=177.19.235.217

#eletro delta
#banco=tecsoft
#host=187.55.208.102

#host=rot.frettalar.com.br
#banco=tecsoft

#host=localhost
#porta=5433
#banco=clamar_mtz

#banco=macromaq
#banco=tecsoft

#banco=gama

#banco=tecsoft
#host=rot.frettalar.com.br

#eletrodelta

#host=10.31.1.1
#eletro delta

#host=201.34.141.99
#host=201.34.141.99

#host=10.16.1.1
#banco=gama

#FRETTA CRICIUMA
#host=suportefretta.dyndns.info
#host=189.115.78.153
#host=200.180.4.80
#host=177.43.63.248
#banco=tecsoft

#banco=agro

#gama
#host=187.52.178.148

#host=189.31.66.218 holding

#VALDIR
#host=201.47.57.59


#zita agro
#banco=zita
#host=186.215.116.35

#kilar
#host=200.175.61.147
#banco=tecsoft
#host=200.146.120.227


MaxColAutenticadora=47

[modulos]
atual=

#disponiveis=adminsistema,estoque,vendas
disponiveis=contasareceber,adminsistema,interlojas,estoque,caixa,vendas,cobranca,entrega,montagens,livrosfiscais,financeiro,sac,bancos,contabil,contaspagar
#disponiveis=repositorio,contasareceber,adminsistema,imoveis,estoque,caixa,cobranca,interlojas,entrega,montagens,imoveis,livrosfiscais,financeiro,sac,bancos,contabil,contaspagar,vendas,producao
#disponiveis=bancos,vendas,estoque,caixa,contaspagar
#disponiveis=vendas

[impressoraetiqueta]
impressora=PDFCreator
tipo=jato
[impressoras]
imprimircarneecf=0
imprimirlinefeednaimpressoramatricial=0
notafiscalservicos=
contrato=
carne=
boleto=
OSP=
SetupProcesso=
ControleProcesso=
fechamentocaixa=EPSON TM-T20 Receipt
notafiscal=PDFCreator
NFCe=EPSON TM-T20 Receipt
Imprimir_recibos_pelo_FastReport=1
Imprimir recibos pelo FastReport=1


[frentecaixa]
#trabalharcomo=sim
imprimircarneecf=1
SetupProcesso=
ControleProcesso=
imprimirlinefeednaimpressoramatricial=1
boleto=Generic / Text Only
OSP=
notafiscalservicos=Generic / Text Only
notafiscal=PDFCreator???
contrato=
fechamentocaixa=Generic / Text Only

[autenticacao]
autenticadora=3
autenticarecf=0
CortarPapel=0

[PCP]
DirExp=
[SPED]
DirSpedFiscal=C:\Clientes\Zita
DirSpedContabil=C:\Clientes\Zita
DirSpedFCont=
DirEFDContribuições=C:\Clientes\Zita
[EXPORTAÇÃO]
DirExportação=N:\Gedovar\clientes\zita
[EXPORTAÇÃO PRODUTOS]
DirExportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[EXPORTAÇÃO NOTAS TRANSFERENCIA]
DirExportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[IMPORTAÇÃO PRODUTOS]
DirImportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[IMPORTAÇÃO NOTAS TRANSFERENCIA]
DirImportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[MovimentacaoDiaria]
Movimentos=




[NFe]
Ambiente=1
TipoEmissao=1
DirEnvio=C:\Unimake\UniNFe\81332553000143\Envio
DirRetorno=C:\Unimake\UniNFe\81332553000143\Retorno
DirEnviados=C:\Unimake\UniNFe\81332553000143\Enviado\Autorizados
DirErros=C:\Unimake\UniNFe\81332553000143\Erro
DirComp=C:\Unimake\UniNFe\81332553000143\compartilha




Visualizar=1
Simplificada=1
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
#ExecNFes=C:\Unimake\UniNFe\uninfe.exe
ExecDANFE=C:\Unimake\UniNFe\unidanfe.exe
NumVias=1
Logotipo=C:\projetos.vcl\apps\tecsoft\imagens\logo.bmp
ModeloDANFE=C:\projetos.vcl\apps\tecsoft\Modelos Relatórios\DANFeNFCeA4.fr3
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
VisualizarVendasOperações=0

#[ecf]
#porta=2
#codigo=11
#velocidadeporta=9600


#octo_NFE=33305
#Tipo_NFE=E
#Operacao_NFE=1
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
#ExecNFe=C:\Unimake\UniNFe\uninfe.exe
VisualizarVendasOperações=0
ExecNFe=C:\Unimake\UniNFe\uninfe.exe


[Outros]
percentualdescontoetiqueta=0,00
CaminhoArquivoImportacao=C:\Users\CPU\Desktop\lista.txt
CaminhoArquivoImportacaoInventario=C:\temp\coletor\temp.txt
[Exportacao]
DirVendas=C:\Users\CPU\Desktop
DirReducoes=C:\Users\CPU\Desktop
[Importacao]
Produtos=C:\teclux\IMPORTA.TXT
Estoques=
Clientes=

[ConsultaComnpras]
PedidosEntreFiliais=1
[impchq]
marca=TSP
tipoporta=Paralela
numeroporta=1

[Reinf]
Ambiente=1




[NFSe]
DirEnvio=C:\Unimake\UniNFSe\10358474000163\Envio 
DirRetorno=C:\Unimake\UniNFSe\10358474000163\Retorno
Ambiente=1
DirErros=C:\Unimake\UniNFSe\10358474000163\Erros
#CertificadoNFSe=C:\Unimake\UniNFSe\81332553000143\12762568.pfx

#[NFSe]
#DirEnvio=C:\Unimake\UniNFSe\10431402000102\nfse\Envio
#DirRetorno=C:\Unimake\UniNFSe\10431402000102\nfse\Retorno

#Ambiente=2
#DirErros=C:\Unimake\UniNFSe\10431402000102\nfse\Erro
#CertificadoNFSe=N:\Beatriz\certificado 2018\13311506_out.pfx
#Ambiente=1
#DirEnvio=C:\Unimake\UNINFSE\82858903000253\Envio
#DirRetorno=C:\Unimake\UNINFSE\82858903000253\Retorno
#DirErros=C:\Unimake\UNINFSE\82858903000253\Erro

#CertificadoNFSe=N:\Beatriz\CertificadoDigital\certificado_jlw.pfx
#CertificadoNFSe=N:\Clientes\apolonia\16406587_out.pfx
CertificadoNFSe=C:\projetos.vcl\Ortho Shops senha ortho1234.pfx
DirSchema=C:\Unimake\UniNFSe\Schemas

[Cobrança Bancária]
Diretorio=C:\lixo
Diretorio Retorno=N:\Clientes\Apolonia\boleto_santander\retorno
Diretorio Retorno PagFor=N:\Gedovar\Pagamento_a_Fornecedores
[NFCe]
DataHoraInicialContingenciaNFCe=
RazaoContingenciaNFCe=
[Empresa_Desenvolvedora]
NomeEmpresaDesenvolvedora=4A4D50324D5154918726690FE7351A08B8DA1AB8A3B54998AD9182F25984D6F1A691935E
CNPJDesenvolvedora=313138666B4A487F10D474D47F1C
IEDesenvolvedora=30
IMDesenvolvedora=30
NomeComercialSistema=544750DA873B27
VersaoPAFECF=3033256466
CodigoMD5=30
LaudoPAFECF=554C40BBE1E6EF23B684
#este é o de produção 1606900015251 
NumeroCredenciamento=31373C605A8A2EE5EF2BE7EA10  

#este é o de homologação SAT: 1606900013429
#NumeroCredenciamento=39303B5092BAAC7C2A8C026D40  

#NumeroCredenciamento=34313A614774D100610DAB17


Endereco1=527775B0BC82341D396F06C924A7D2E070F9485D13BEE8620724A12B
Endereco2=466E7E0D1506B989242272B08BF2943A
Telefone=34393F6BB1AF72F1BEF3
Contato=4A4D50324D5154918726690F
DataLaudoPAFECF=303724656775486A4B61
[NFeEntrada]
DirNotasEntrada=C:\projetos.vcl\apps\tecsoft\XMLTemp


#[tef]
#Tipo=1
#Vias=1
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe
#TipoTef=gpPayGo


#[tef]
#Tipo=1
#Vias=
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe

#[tef]
#Tipo=1
#Vias=
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe
[BlocoX]
TransmitirBlocoX=0

#[ecf]
#porta=2
#[tef]
#Tipo=1
#Vias=1
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe

#[tef]
#Tipo=1
#Vias=1
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe



# Praiana KObrasol nfce CSC C8CFD17D-202C-45C8-8855-199C740D135A  ID TOKEN 000001
# ambiente de homologação C950DA54-721B-4886-8BA0-D73E654586F3 

#C950DA54-721B-4886-8BA0-D73E654586F3
#[tef]
#Tipo=1
#Vias=1
#DirReq=C:\TEF_Dial\Req
#DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe

#[tef]
#Tipo=1
#Vias=1
#DirReq=C:\TEF_Dial\Req
##DirResp=C:\TEF_Dial\Resp
#Exec=C:\TEF_Dial\tef_dial.exe

#DirReq=C:\Auttar_TefIP\req
#DirResp=C:\Auttar_TefIP\resp
#Exec=C:\Program Files\Auttar\IntegradorTEF-IP\IntegradorTEF-IP.exe
#TipoTef=gpTefAuttar
#TipoTef=gpPayGo
#LogDebug=True
