inherited frmCadastroTiposPagamentos: TfrmCadastroTiposPagamentos
  Left = 475
  Top = 192
  ActiveControl = edtCodigo
  Caption = 'Cadastro de Tipos de Pagamentos'
  ClientHeight = 132
  ClientWidth = 722
  FormStyle = fsMDIChild
  Visible = True
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Left = 0
    Top = 40
    Width = 722
    Height = 92
    Align = alClient
    BorderWidth = 3
    Visible = True
    inherited bvlBotoesEd: TBevel
      Left = 78
      Top = 13
      Visible = False
    end
    object ckbPagamento: TDBCheckBox
      Left = 405
      Top = 25
      Width = 140
      Height = 17
      Caption = 'Com sa'#237'da do caixa'
      DataField = 'saidadocaixa'
      DataSource = dtmCadastroTiposPagamentos.dsrTiposPagamentos
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      ValueChecked = 'True'
      ValueUnchecked = 'False'
    end
    object gbxDescricao: TGroupBox
      Left = 85
      Top = 10
      Width = 315
      Height = 36
      Caption = 'DESCRI'#199#195'O'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object edtDescricao: TDBEditTexto
        Left = 2
        Top = 10
        Width = 310
        Height = 23
        DataField = 'descricao'
        DataSource = dtmCadastroTiposPagamentos.dsrTiposPagamentos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxCodigo: TGroupBox
      Left = 10
      Top = 10
      Width = 65
      Height = 36
      Caption = 'C'#211'DIGO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object edtCodigo: TtecDbEditFind
        Left = 2
        Top = 10
        Width = 60
        Height = 23
        Alignment = taLeftJustify
        DataField = 'codigo'
        DataSource = dtmCadastroTiposPagamentos.dsrTiposPagamentos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Group = 'TiposPagamentos'
        MaxLength = 3
        Maximo = 0
        Minimo = 37353
        Adicional = 0
        Opcional = True
        ParentFont = False
        TabOrder = 0
        PermitirZero = False
        PermitirNulo = False
        Operacao = opATRIBUICAO
        Parameter = 'codigo'
        ActiveSetControls = True
        DenyInsert = True
        NoSetControls = <>
        SetControls = <>
      end
    end
    object gbxEventos: TGroupBox
      Left = 10
      Top = 52
      Width = 540
      Height = 36
      Caption = 'EVENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      inline fraConsultaEventos: TfraConsultaCodigoContabil
        Left = 5
        Top = 10
        Width = 531
        Height = 23
        HorzScrollBar.Range = 497
        VertScrollBar.Range = 23
        AutoScroll = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        inherited dtxDescricao: TtecDBText
          Width = 443
          DataField = 'descricao'
          DataSource = fraConsultaEventos.dsrProcuraEventos
        end
        inherited edfCodigo: TtecDBFindLookup
          DataField = 'codigo'
          DataSource = fraConsultaEventos.dsrProcuraEventos
          Group = 'Eventos'
          MaxLength = 3
          OnFound = nil
          Operacao = opPESQUISA
          Parameter = 'codigo'
          ActiveSetControls = False
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
        end
      end
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 722
    inherited tblBarra: TToolBar
      Width = 497
    end
  end
end
