library ecfbematech;

uses
  SysUtils,
  Classes,
  bbbema in 'bbbema.pas',
  ctbematech in '../ctbematech.pas';

{$SONAME 'tececfbematech.so'}
{$SOPREFIX 'tec'}
{$SOVERSION '1.0'}

exports
    Bema_AlteraSimboloMoeda                    name 'Bematech_FI_AlteraSimboloMoeda',
    Bema_ProgramaAliquota                      name 'Bematech_FI_ProgramaAliquota',
    Bema_ProgramaHorarioVerao                  name 'Bematech_FI_ProgramaHorarioVerao',
    Bema_NomeiaDepartamento                    name 'Bematech_FI_NomeiaDepartamento',
    Bema_NomeiaTotalizadorNaoSujeitoIcms       name 'Bematech_FI_NomeiaTotalizadorNaoSujeitoIcms',
    Bema_ProgramaArredondamento                name 'Bematech_FI_ProgramaArredondamento',
    Bema_ProgramaTruncamento                   name 'Bematech_FI_ProgramaTruncamento',
    Bema_LinhasEntreCupons                     name 'Bematech_FI_LinhasEntreCupons',
    Bema_EspacoEntreLinhas                     name 'Bematech_FI_EspacoEntreLinhas',
    Bema_AbreCupom                             name 'Bematech_FI_AbreCupom',
    Bema_VendeItem                             name 'Bematech_FI_VendeItem',
    Bema_VendeItemDepartamento                 name 'Bematech_FI_VendeItemDepartamento',
    Bema_CancelaItemAnterior                   name 'Bematech_FI_CancelaItemAnterior',
    Bema_CancelaItemGenerico                   name 'Bematech_FI_CancelaItemGenerico',
    Bema_CancelaCupom                          name 'Bematech_FI_CancelaCupom',
    Bema_FechaCupomResumido                    name 'Bematech_FI_FechaCupomResumido',
    Bema_FechaCupom                            name 'Bematech_FI_FechaCupom',
    Bema_ResetaImpressora                      name 'Bematech_FI_ResetaImpressora',
    Bema_IniciaFechamentoCupom                 name 'Bematech_FI_IniciaFechamentoCupom',
    Bema_EfetuaFormaPagamento                  name 'Bematech_FI_EfetuaFormaPagamento',
    Bema_TerminaFechamentoCupom                name 'Bematech_FI_TerminaFechamentoCupom',
    Bema_UsaUnidadeMedida                      name 'Bematech_FI_UsaUnidadeMedida',
    Bema_AumentaDescricaoItem                  name 'Bematech_FI_AumentaDescricaoItem',
    Bema_LeituraX                              name 'Bematech_FI_LeituraX',
    Bema_ReducaoZ                              name 'Bematech_FI_ReducaoZ',
    Bema_RelatorioGerencial                    name 'Bematech_FI_RelatorioGerencial',
    Bema_FechaRelatorioGerencial               name 'Bematech_FI_FechaRelatorioGerencial',
    Bema_LeituraMemoriaFiscalData              name 'Bematech_FI_LeituraMemoriaFiscalData',
    Bema_LeituraMemoriaFiscalReducao           name 'Bematech_FI_LeituraMemoriaFiscalReducao',
    Bema_LeituraMemoriaFiscalSerialData        name 'Bematech_FI_LeituraMemoriaFiscalSerialData',
    Bema_LeituraMemoriaFiscalSerialReducao     name 'Bematech_FI_LeituraMemoriaFiscalSerialReducao',
    Bema_RecebimentoNaoFiscal                  name 'Bematech_FI_RecebimentoNaoFiscal',
    Bema_AbreComprovanteNaoFiscalVinculado     name 'Bematech_FI_AbreComprovanteNaoFiscalVinculado',
    Bema_UsaComprovanteNaoFiscalVinculado      name 'Bematech_FI_UsaComprovanteNaoFiscalVinculado',
    Bema_FechaComprovanteNaoFiscalVinculado    name 'Bematech_FI_FechaComprovanteNaoFiscalVinculado',
    Bema_Sangria                               name 'Bematech_FI_Sangria',
    Bema_Suprimento                            name 'Bematech_FI_Suprimento',
    Bema_NumeroSerie                           name 'Bematech_FI_NumeroSerie',
    Bema_SubTotal                              name 'Bematech_FI_SubTotal',
    Bema_NumeroCupom                           name 'Bematech_FI_NumeroCupom',
    Bema_LeituraXSerial                        name 'Bematech_FI_LeituraXSerial',
    Bema_VersaoFirmware                        name 'Bematech_FI_VersaoFirmware',
    Bema_CGC_IE                                name 'Bematech_FI_CGC_IE',
    Bema_GrandeTotal                           name 'Bematech_FI_GrandeTotal',
    Bema_Cancelamentos                         name 'Bematech_FI_Cancelamentos',
    Bema_Descontos                             name 'Bematech_FI_Descontos',
    Bema_NumeroOperacoesNaoFiscais             name 'Bematech_FI_NumeroOperacoesNaoFiscais',
    Bema_NumeroCuponsCancelados                name 'Bematech_FI_NumeroCuponsCancelados',
    Bema_NumeroIntervencoes                    name 'Bematech_FI_NumeroIntervencoes',
    Bema_NumeroReducoes                        name 'Bematech_FI_NumeroReducoes',
    Bema_NumeroSubstituicoesProprietario       name 'Bematech_FI_NumeroSubstituicoesProprietario',
    Bema_UltimoItemVendido                     name 'Bematech_FI_UltimoItemVendido',
    Bema_ClicheProprietario                    name 'Bematech_FI_ClicheProprietario',
    Bema_NumeroCaixa                           name 'Bematech_FI_NumeroCaixa',
    Bema_NumeroLoja                            name 'Bematech_FI_NumeroLoja',
    Bema_SimboloMoeda                          name 'Bematech_FI_SimboloMoeda',
    Bema_MinutosLigada                         name 'Bematech_FI_MinutosLigada',
    Bema_MinutosImprimindo                     name 'Bematech_FI_MinutosImprimindo',
    Bema_VerificaModoOperacao                  name 'Bematech_FI_VerificaModoOperacao',
    Bema_VerificaEpromConectada                name 'Bematech_FI_VerificaEpromConectada',
    Bema_FlagsFiscais                          name 'Bematech_FI_FlagsFiscais',
    Bema_ValorPagoUltimoCupom                  name 'Bematech_FI_ValorPagoUltimoCupom',
    Bema_DataHoraImpressora                    name 'Bematech_FI_DataHoraImpressora',
    Bema_ContadoresTotalizadoresNaoFiscais     name 'Bematech_FI_ContadoresTotalizadoresNaoFiscais',
    Bema_VerificaTotalizadoresNaoFiscais       name 'Bematech_FI_VerificaTotalizadoresNaoFiscais',
    Bema_DataHoraReducao                       name 'Bematech_FI_DataHoraReducao',
    Bema_DataMovimento                         name 'Bematech_FI_DataMovimento',
    Bema_VerificaTruncamento                   name 'Bematech_FI_VerificaTruncamento',
    Bema_Acrescimos                            name 'Bematech_FI_Acrescimos',
    Bema_ContadorBilhetePassagem               name 'Bematech_FI_ContadorBilhetePassagem',
    Bema_VerificaRecebimentoNaoFiscal          name 'Bematech_FI_VerificaRecebimentoNaoFiscal',
    Bema_VerificaDepartamentos                 name 'Bematech_FI_VerificaDepartamentos',
    Bema_VerificaTipoImpressora                name 'Bematech_FI_VerificaTipoImpressora',
    Bema_VerificaTotalizadoresParciais         name 'Bematech_FI_VerificaTotalizadoresParciais',
    Bema_RetornoAliquotas                      name 'Bematech_FI_RetornoAliquotas',
    Bema_DadosUltimaReducao                    name 'Bematech_FI_DadosUltimaReducao',
    Bema_MonitoramentoPapel                    name 'Bematech_FI_MonitoramentoPapel',
    Bema_VerificaIndiceAliquotasIss            name 'Bematech_FI_VerificaIndiceAliquotasIss',
    Bema_ValorFormaPagamento                   name 'Bematech_FI_ValorFormaPagamento',
    Bema_Autenticacao                          name 'Bematech_FI_Autenticacao',
    Bema_ProgramaCaracterAutenticacao          name 'Bematech_FI_ProgramaCaracterAutenticacao',
    Bema_AcionaGaveta                          name 'Bematech_FI_AcionaGaveta',
    Bema_VerificaEstadoGaveta                  name 'Bematech_FI_VerificaEstadoGaveta',
    Bema_ProgramaMoedaSingular                 name 'Bematech_FI_ProgramaMoedaSingular',
    Bema_ProgramaMoedaPlural                   name 'Bematech_FI_ProgramaMoedaPlural',
    Bema_CancelaImpressaoCheque                name 'Bematech_FI_CancelaImpressaoCheque',
    Bema_VerificaStatusCheque                  name 'Bematech_FI_VerificaStatusCheque',
    Bema_ImprimeCheque                         name 'Bematech_FI_ImprimeCheque',
    Bema_AbrePortaSerial                       name 'Bematech_FI_AbrePortaSerial',
    Bema_FechaPortaSerial                      name 'Bematech_FI_FechaPortaSerial',
    Bema_VerificaFormaPagamento                name 'Bematech_FI_VerificaFormaPagamento',
    Bema_ProgramaFormasPagamento               name 'Bematech_FI_ProgramaFormasPagamento',
    Bema_ContadorSequencial                    name 'Bematech_FI_ContadorSequencial',
    Bema_ContadoresTotalizadoresNaoSujeitos    name 'Bematech_FI_ContadoresTotalizadoresNaoSujeitos',
    Bema_ImprimeChequeBR400                    name 'Bematech_FI_ImprimeChequeBR400',
    Bema_LeituraCheque                         name 'Bematech_FI_LeituraCheque';

procedure SignalHandler(Reason: Integer);
begin
  if Reason = 0 then
    UnhookSignal(RTL_SIGDEFAULT);
end;

begin
  HookSignal(RTL_SIGDEFAULT);
  DllProc := @SignalHandler;
end.
