inherited frmCadastroTabelaMontagem: TfrmCadastroTabelaMontagem
  Left = 522
  Top = 175
  AutoSize = False
  Caption = 'Cadastro de Tabela de Montagens'
  ClientHeight = 279
  ClientWidth = 384
  FormStyle = fsMDIChild
  Visible = True
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Left = 12
    Width = 341
    inherited bvlBotoesEd: TBevel
      Left = 1
      Top = 1
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 384
    inherited tblBarra: TToolBar
      Width = 159
    end
  end
  object pnlfundojanela: TPanel
    Left = 0
    Top = 40
    Width = 384
    Height = 239
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 3
    TabOrder = 2
    object gbxCodigo: TGroupBox
      Left = 10
      Top = 10
      Width = 65
      Height = 36
      Caption = 'C'#211'DIGO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object edfCodigo: TtecDbEditFind
        Left = 2
        Top = 10
        Width = 60
        Height = 23
        DataField = 'codigo'
        DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Group = 'TabelaMontagem'
        MaxLength = 4
        Maximo = 0
        Minimo = 37353
        Adicional = 0
        Opcional = True
        ParentFont = False
        TabOrder = 0
        PermitirZero = False
        PermitirNulo = False
        Operacao = opATRIBUICAO
        Parameter = 'codigo'
        ActiveSetControls = True
        DenyInsert = True
        NoSetControls = <>
        SetControls = <>
      end
    end
    object rgpTipo: TtecDBRadioGroup
      Left = 10
      Top = 56
      Width = 65
      Height = 67
      Caption = 'Tipo'
      TabOrder = 2
      TabStop = False
      DataField = 'tipovalor'
      DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
      object rbnPercentual: TtecRadioButton
        Left = 16
        Top = 20
        Width = 37
        Height = 17
        Caption = '%'
        Checked = True
        TabOrder = 0
        TabStop = True
        Value = '%'
      end
      object rbnValor: TtecRadioButton
        Left = 16
        Top = 44
        Width = 37
        Height = 17
        Caption = '$'
        TabOrder = 1
        Value = 'V'
      end
    end
    object gbxDescricao: TGroupBox
      Left = 85
      Top = 10
      Width = 295
      Height = 36
      Caption = 'DESCRI'#199#195'O'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object edtDescricao: TDBEditTexto
        Left = 2
        Top = 10
        Width = 290
        Height = 23
        DataField = 'descricao'
        DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
      end
    end
    object gbxValoresMontagem: TGroupBox
      Left = 85
      Top = 57
      Width = 296
      Height = 72
      Caption = 'VALORES DA MONTAGENS'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      object gbxNaLoja: TGroupBox
        Left = 0
        Top = 36
        Width = 100
        Height = 36
        Caption = 'NA LOJA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object edtValorLoja: TDBEditNumero
          Left = 2
          Top = 10
          Width = 95
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = True
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 9
          DataField = 'valorloja'
          DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
        end
      end
      object gbxForaLoja: TGroupBox
        Left = 98
        Top = 21
        Width = 198
        Height = 51
        Caption = 'FORA DA LOJA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object gbxNaRegiao: TGroupBox
          Left = 0
          Top = 15
          Width = 100
          Height = 36
          Caption = 'NA REGI'#195'O'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object edtValorDentro: TDBEditNumero
            Left = 2
            Top = 10
            Width = 95
            Height = 23
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -12
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            MaxLength = -1
            ParentFont = False
            TabOrder = 0
            Mascara = True
            Alignment = taLeftJustify
            TipoMascara = tmGERAL
            NrDecimal = 2
            Decimais = True
            Negativo = False
            Tamanho = 9
            DataField = 'valordentro'
            DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
          end
        end
        object gbxForaRegiao: TGroupBox
          Left = 98
          Top = 15
          Width = 100
          Height = 36
          Caption = 'FORA DA REGI'#195'O'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          object edtValorFora: TDBEditNumero
            Left = 2
            Top = 10
            Width = 95
            Height = 23
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -12
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            MaxLength = -1
            ParentFont = False
            TabOrder = 0
            Mascara = True
            Alignment = taLeftJustify
            TipoMascara = tmGERAL
            NrDecimal = 2
            Decimais = True
            Negativo = False
            Tamanho = 9
            DataField = 'valorfora'
            DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
          end
        end
      end
    end
    object gbxObservacoes: TGroupBox
      Left = 10
      Top = 136
      Width = 371
      Height = 93
      Caption = 'OBSERVA'#199#213'ES'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      object mmoObservacoes: TtecDBMemo
        Left = 2
        Top = 14
        Width = 367
        Height = 77
        Align = alClient
        DataField = 'observacoes'
        DataSource = dtmCadastroTabelaMontagem.dsrTabelaMontagem
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
    end
  end
end
