inherited frmRequisicoesOSPProdutos: TfrmRequisicoesOSPProdutos
  Left = 447
  Top = 209
  ActiveControl = edtQuantidade
  Caption = 'Cadastro de Produto Composto'
  ClientHeight = 191
  ClientWidth = 812
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Width = 596
    inherited bvlBotoesEd: TBevel
      Left = 135
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 812
    TabOrder = 2
    inherited tblBarra: TToolBar
      Width = 587
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
    inherited tblBarraCadastro: TToolBar
      inherited sbnIncluir: TSpeedButton
        Enabled = False
        Visible = False
      end
      inherited sbnExcluir: TSpeedButton
        Visible = False
      end
    end
  end
  object pnlFundoJanela: TPanel
    Left = 0
    Top = 40
    Width = 812
    Height = 151
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object gbxConsulta: TGroupBox
      Left = 0
      Top = 0
      Width = 812
      Height = 151
      Align = alClient
      TabOrder = 0
      object gbxComposto: TGroupBox
        Left = 8
        Top = 8
        Width = 722
        Height = 36
        Caption = 'PRODUTO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object dtxProduto: TtecDBText
          Left = 234
          Top = 10
          Width = 485
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'descricao'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
        object dtxCodigoProduto: TtecDBText
          Left = 2
          Top = 10
          Width = 230
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'codigovisual'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          Alignment = taLeftJustify
        end
      end
      object gbxQuantidade: TGroupBox
        Left = 310
        Top = 48
        Width = 142
        Height = 36
        Caption = 'QUANTIDADE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object edtQuantidade: TDBEditNumero
          Left = 2
          Top = 10
          Width = 136
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = False
          TipoMascara = tmQUANTIDADE
          NrDecimal = 0
          Decimais = False
          Negativo = False
          Tamanho = 0
          DataField = 'quantidadees'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
        end
      end
      object gbxOrigem: TGroupBox
        Left = 732
        Top = 8
        Width = 77
        Height = 36
        Caption = 'ORIGEM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object dtxOrigem: TtecDBText
          Left = 2
          Top = 10
          Width = 71
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'Origem'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxSolicitada: TGroupBox
        Left = 7
        Top = 48
        Width = 146
        Height = 36
        Caption = 'SOLICITADA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object dtxSolicitada: TtecDBText
          Left = 2
          Top = 10
          Width = 139
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'quantidade'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxLiberada: TGroupBox
        Left = 159
        Top = 48
        Width = 146
        Height = 36
        Caption = 'LIBERADA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object dtxLiberada: TtecDBText
          Left = 2
          Top = 10
          Width = 139
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'quantidadeliberada'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxSaldo: TGroupBox
        Left = 458
        Top = 48
        Width = 146
        Height = 36
        Caption = 'SALDO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        object dtxSaldo: TtecDBText
          Left = 2
          Top = 10
          Width = 139
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'saldocomquantidadees'
          DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object rgbTipodeOperacao: TtecDBRadioGroup
        Left = 8
        Top = 88
        Width = 121
        Height = 57
        Caption = 'TIPO DA OPERA'#199#195'O'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        TabStop = False
        DataField = 'operacao'
        DataSource = dtmRequisicoesOSP.dsrRequisicoesOSP
        object tecRadioButton1: TtecRadioButton
          Left = 8
          Top = 16
          Width = 97
          Height = 17
          Caption = 'ENTRADA'
          TabOrder = 0
          Value = 'E'
        end
        object tecRadioButton2: TtecRadioButton
          Left = 8
          Top = 34
          Width = 97
          Height = 17
          Caption = 'SA'#205'DA'
          Checked = True
          TabOrder = 1
          TabStop = True
          Value = 'S'
        end
      end
    end
  end
end
