inherited frmCadastroDuplicatas: TfrmCadastroDuplicatas
  Left = 292
  Top = 219
  ActiveControl = edtDataDuplicata
  Caption = 'Cadastro de Duplicatas'
  ClientHeight = 277
  ClientWidth = 672
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlTopMenu: TPanel
    Width = 672
    TabOrder = 2
    inherited tblBarra: TToolBar
      Width = 447
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
  end
  object pnlFundoJanela: TPanel
    Left = 0
    Top = 45
    Width = 672
    Height = 232
    Align = alClient
    BorderWidth = 3
    TabOrder = 1
    object gbxDuplicatas: TGroupBox
      Left = 4
      Top = 4
      Width = 664
      Height = 224
      Align = alClient
      TabOrder = 0
      object gbxJuros: TGroupBox
        Left = 173
        Top = 47
        Width = 143
        Height = 75
        Caption = 'JUROS DI'#193'RIOS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object lblJuros: TLabel
          Left = 107
          Top = 31
          Width = 30
          Height = 12
          Alignment = taRightJustify
          Caption = 'VALOR'
        end
        object rgbTipoJuros: TtecDBRadioGroup
          Left = 3
          Top = 17
          Width = 65
          Height = 55
          Caption = 'TIPO'
          TabOrder = 1
          TabStop = False
          DataField = 'tipojuros'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
          object ckbPorcentagemJuros: TtecRadioButton
            Left = 13
            Top = 14
            Width = 42
            Height = 17
            Caption = '%'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            Value = '%'
          end
          object ckbValorJuros: TtecRadioButton
            Left = 13
            Top = 32
            Width = 42
            Height = 17
            Caption = 'R$'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            Value = 'V'
          end
        end
        object edtJuros: TDBEditNumero
          Left = 71
          Top = 47
          Width = 68
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = True
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 9
          DataField = 'juros'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
        end
      end
      object gbxMulta: TGroupBox
        Left = 9
        Top = 46
        Width = 143
        Height = 75
        Caption = 'MULTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object lblMulta: TLabel
          Left = 107
          Top = 29
          Width = 30
          Height = 12
          Alignment = taRightJustify
          Caption = 'VALOR'
        end
        object rgbTipoMulta: TtecDBRadioGroup
          Left = 3
          Top = 14
          Width = 65
          Height = 55
          Caption = 'TIPO'
          TabOrder = 1
          TabStop = False
          DataField = 'tipomulta'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
          object ckbPorcentagemMulta: TtecRadioButton
            Left = 13
            Top = 14
            Width = 42
            Height = 17
            Caption = '%'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            Value = '%'
          end
          object ckbValorMulta: TtecRadioButton
            Left = 13
            Top = 32
            Width = 43
            Height = 17
            Caption = 'R$'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            Value = 'V'
          end
        end
        object edtMulta: TDBEditNumero
          Left = 71
          Top = 44
          Width = 68
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = True
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 9
          DataField = 'multa'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
        end
      end
      object gbxObs: TGroupBox
        Left = 2
        Top = 119
        Width = 660
        Height = 103
        Align = alBottom
        Caption = 'OBSERVA'#199#213'ES DA DUPLICATA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        object mmoObsDuplicatas: TtecDBMemo
          Left = 2
          Top = 16
          Width = 650
          Height = 87
          DataField = 'observacao'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          WantTabs = True
        end
      end
      object gbxDataVencto: TGroupBox
        Left = 9
        Top = 2
        Width = 80
        Height = 40
        Caption = 'DATA VENCTO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object edtDataDuplicata: TDBEditData
          Left = 3
          Top = 12
          Width = 75
          Height = 24
          Alignment = taLeftJustify
          DataField = 'datavencto'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          Maximo = 3650
          Minimo = 37353
          Adicional = 0
          ParentFont = False
          TabOrder = 0
          Opcional = True
        end
      end
      object gbxValorVecnto: TGroupBox
        Left = 96
        Top = 2
        Width = 110
        Height = 40
        Caption = 'VALOR VENCTO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object edtValorDuplicata: TDBEditNumero
          Left = 3
          Top = 12
          Width = 105
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = True
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 12
          DataField = 'valorvencto'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
        end
      end
      object gbxDesctoDuplicata: TGroupBox
        Left = 213
        Top = 2
        Width = 110
        Height = 40
        Caption = 'DESCONTO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object edtDescontoDuplicata: TDBEditNumero
          Left = 3
          Top = 12
          Width = 105
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = True
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 7
          DataField = 'valordesconto'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
        end
      end
      object gbxValorPagar: TGroupBox
        Left = 344
        Top = 2
        Width = 237
        Height = 67
        Caption = 'VALOR A PAGAR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 7
        object dtxValoraPagar: TtecDBText
          Left = 24
          Top = 21
          Width = 186
          Height = 30
          TabStop = False
          BorderStyle = bsNone
          Color = clBtnFace
          DataField = 'ValorAPagar'
          DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -19
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxBancoCobranca: TGroupBox
        Left = 329
        Top = 83
        Width = 328
        Height = 40
        Caption = 'BANCO EM COBRAN'#199'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        inline fraConsultaBanco: TfraConsultaCodigo
          Left = 4
          Top = 12
          Width = 322
          Height = 25
          HorzScrollBar.Range = 318
          VertScrollBar.Range = 23
          AutoScroll = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          inherited dtxDescricao: TtecDBText
            Width = 230
            Height = 24
            DataField = 'Sigla'
            DataSource = fraConsultaBanco.dsrProcuraBanco
            Font.Height = -13
            Font.Name = 'Arial'
          end
          inherited edfCodigo: TtecDBFindLookup
            Height = 24
            DataField = 'bancocobranca'
            DataSource = dtmCadastroNotasFiscais.dsrDuplicatas
            Font.Height = -13
            Font.Name = 'Arial'
            MaxLength = 6
            LookupField = 'Codigo'
            LookupSource = fraConsultaBanco.dsrProcuraBanco
            LookupQueryParameter = 'codigo'
            Parameter = ' '
            ActiveSetControls = False
            DenyInsert = False
            NoSetControls = <>
            SetControls = <>
            LookupParameter = 'codigo'
          end
        end
      end
    end
  end
end
