inherited frmCadastroProdutoCompostoFitas: TfrmCadastroProdutoCompostoFitas
  Left = 532
  Top = 203
  Caption = 'Cadastro de Produto Composto de Fitas'
  ClientHeight = 179
  ClientWidth = 733
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Width = 596
    inherited bvlBotoesEd: TBevel
      Left = 135
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 733
    TabOrder = 2
    inherited tblBarra: TToolBar
      Width = 508
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
    inherited tblBarraCadastro: TToolBar
      inherited sbnIncluir: TSpeedButton
        Enabled = False
      end
    end
  end
  object pnlFundoJanela: TPanel
    Left = 0
    Top = 40
    Width = 733
    Height = 139
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object Label1: TLabel
      Left = 95
      Top = 104
      Width = 7
      Height = 16
      Caption = 'x'
    end
    object Label2: TLabel
      Left = 193
      Top = 104
      Width = 8
      Height = 15
      Caption = 'B'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
    end
    object gbxComposto: TGroupBox
      Left = 6
      Top = 5
      Width = 722
      Height = 36
      Caption = 'COMPOSTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object dtxProduto: TtecDBText
        Left = 234
        Top = 10
        Width = 485
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'descricaolc'
        DataSource = dtmCadastroProdutos.dsrProdutos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
      object dtxCodigoProduto: TtecDBText
        Left = 2
        Top = 10
        Width = 230
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'codigovisual'
        DataSource = dtmCadastroProdutos.dsrProdutos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Alignment = taLeftJustify
      end
    end
    object gbxEspessura_fita: TGroupBox
      Left = 7
      Top = 92
      Width = 85
      Height = 35
      Caption = 'ESPESSURA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      object edtEspessura_fita: TDBEditTexto
        Left = 4
        Top = 10
        Width = 76
        Height = 23
        DataField = 'espessura'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxLargura_fita: TGroupBox
      Left = 106
      Top = 92
      Width = 85
      Height = 35
      Caption = 'LARGURA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      object edtLargura_fita: TDBEditTexto
        Left = 4
        Top = 10
        Width = 76
        Height = 23
        DataField = 'largura'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxLiga_fita: TGroupBox
      Left = 204
      Top = 91
      Width = 45
      Height = 36
      Caption = 'LIGA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      object edtLiga_fita: TDBEditTexto
        Left = 2
        Top = 10
        Width = 39
        Height = 23
        DataField = 'liga'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxVolta_fita: TGroupBox
      Left = 253
      Top = 91
      Width = 50
      Height = 36
      Caption = 'VOLTA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      object edtVolta_fita: TDBEditNumero
        Left = 2
        Top = 10
        Width = 43
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = False
        TipoMascara = tmGERAL
        NrDecimal = 0
        Decimais = False
        Negativo = False
        Tamanho = 9
        DataField = 'nrvoltas'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
      end
    end
    object gbxqtidadeporgrama_fita: TGroupBox
      Left = 308
      Top = 91
      Width = 113
      Height = 36
      Caption = 'QTD (g / pe'#231'a)'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      object edtqtidadeporgrama_fita: TDBEditNumero
        Left = 3
        Top = 10
        Width = 107
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = True
        TipoMascara = tmGERAL
        NrDecimal = 8
        Decimais = True
        Negativo = False
        Tamanho = 15
        DataField = 'gramasporpeca'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
      end
    end
    object gbxComponente: TGroupBox
      Left = 8
      Top = 47
      Width = 213
      Height = 36
      Caption = 'COMPONENTE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object flkCodigoProduto: TtecDBText
        Left = 4
        Top = 11
        Width = 205
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'componente'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFitas
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
    end
  end
end
