inherited frmCadastroAdicoes: TfrmCadastroAdicoes
  Left = 593
  Top = 282
  ActiveControl = edtMercadoria
  Caption = 'Cadastro de Adi'#231#245'es'
  ClientHeight = 169
  ClientWidth = 597
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Left = 8
    Top = 26
    TabOrder = 12
  end
  inherited pnlTopMenu: TPanel
    Width = 597
    TabOrder = 13
    inherited tblBarra: TToolBar
      Width = 372
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
  end
  object gbxFabricanteAdicao: TGroupBox
    Left = 69
    Top = 45
    Width = 527
    Height = 36
    Caption = 'FABRICANTE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 15
    inline fraConsultaCodigoFabricante: TfraConsultaCodigo
      Left = 2
      Top = 10
      Width = 522
      Height = 23
      HorzScrollBar.Range = 522
      VertScrollBar.Range = 23
      AutoScroll = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      inherited dtxDescricao: TtecDBText
        Width = 434
        DataField = 'nome'
        DataSource = fraConsultaCodigoFabricante.dsrProcuraCliente
      end
      inherited edfCodigo: TtecDBFindLookup
        DataField = 'fabricante'
        DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
        MaxLength = 6
        LookupField = 'codigo'
        LookupSource = fraConsultaCodigoFabricante.dsrProcuraCliente
        LookupQueryParameter = 'codigo'
        Parameter = ' '
        ActiveSetControls = False
        DenyInsert = False
        NoSetControls = <>
        SetControls = <>
        LookupParameter = 'codigo'
      end
    end
  end
  object gbxNumeroAdicao: TGroupBox
    Left = 0
    Top = 45
    Width = 65
    Height = 40
    Caption = 'N'#218'MERO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 14
    object dtxNumeroAdicao: TtecDBText
      Left = 2
      Top = 10
      Width = 61
      Height = 40
      TabStop = False
      Color = clBtnFace
      DataField = 'numero'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -27
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
      Alignment = taLeftJustify
    end
  end
  object gbxMercadoria: TGroupBox
    Left = 0
    Top = 87
    Width = 95
    Height = 36
    Caption = 'MERCADORIA'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object edtMercadoria: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'mercadoria'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxPIS: TGroupBox
    Left = 0
    Top = 127
    Width = 95
    Height = 36
    Caption = 'PIS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 6
    object edtPIS: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'pis'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxCOFINS: TGroupBox
    Left = 100
    Top = 127
    Width = 95
    Height = 36
    Caption = 'COFINS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 7
    object edtCOFINS: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'cofins'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxSISCOMEX: TGroupBox
    Left = 200
    Top = 127
    Width = 95
    Height = 36
    Caption = 'SISCOMEX'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 8
    object edtSISCOMEX: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'siscomex'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxBaseICMS: TGroupBox
    Left = 300
    Top = 127
    Width = 95
    Height = 36
    Caption = 'BASE ICMS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 9
    object edtBaseICMS: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'baseicms'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxValorICMS: TGroupBox
    Left = 501
    Top = 127
    Width = 95
    Height = 36
    Caption = 'VALOR ICMS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 11
    object edtValorICMS: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'valoricms'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxFrete: TGroupBox
    Left = 100
    Top = 87
    Width = 95
    Height = 36
    Caption = 'FRETE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    object edtFrete: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'frete'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxEmbalagem: TGroupBox
    Left = 200
    Top = 87
    Width = 95
    Height = 36
    Caption = 'EMBALAGEM'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    object edtEmbalagem: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'embalagem'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxTHC: TGroupBox
    Left = 300
    Top = 87
    Width = 95
    Height = 36
    Caption = 'THC'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    object edtTHC: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'thc'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxII: TGroupBox
    Left = 400
    Top = 87
    Width = 95
    Height = 36
    Caption = 'II'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 4
    object edtII: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'ii'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxIPI: TGroupBox
    Left = 500
    Top = 87
    Width = 95
    Height = 36
    Caption = 'IPI'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    object edtIPI: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'ipi'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
  object gbxAliquotaICMS: TGroupBox
    Left = 398
    Top = 129
    Width = 95
    Height = 36
    Caption = 'AL'#205'QUOTA ICMS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 10
    object DBEditNumero1: TDBEditNumero
      Left = 2
      Top = 10
      Width = 90
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 9
      DataField = 'aliquotaicms'
      DataSource = dtmCadastroNotasFiscais.dsrAdicoesImportacao
    end
  end
end
