inherited frmCadastroProdutoCompostoFios: TfrmCadastroProdutoCompostoFios
  Left = 478
  Top = 181
  Caption = 'Cadastro de Produto Composto de Fios'
  ClientHeight = 174
  ClientWidth = 735
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Width = 596
    inherited bvlBotoesEd: TBevel
      Left = 135
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 735
    TabOrder = 2
    inherited tblBarra: TToolBar
      Width = 510
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
    inherited tblBarraCadastro: TToolBar
      inherited sbnIncluir: TSpeedButton
        Enabled = False
      end
    end
  end
  object pnlFundoJanela: TPanel
    Left = 0
    Top = 40
    Width = 735
    Height = 134
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object D: TLabel
      Left = 82
      Top = 107
      Width = 9
      Height = 16
      Caption = 'D'
    end
    object gbxComposto: TGroupBox
      Left = 6
      Top = 5
      Width = 722
      Height = 36
      Caption = 'COMPOSTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object dtxProduto: TtecDBText
        Left = 234
        Top = 10
        Width = 485
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'descricaolc'
        DataSource = dtmCadastroProdutos.dsrProdutos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
      object dtxCodigoProduto: TtecDBText
        Left = 2
        Top = 10
        Width = 230
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'codigovisual'
        DataSource = dtmCadastroProdutos.dsrProdutos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Alignment = taLeftJustify
      end
    end
    object gbxBitola_fio: TGroupBox
      Left = 7
      Top = 94
      Width = 73
      Height = 35
      Caption = 'BITOLA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      object edtBitola_fio: TDBEditTexto
        Left = 2
        Top = 10
        Width = 69
        Height = 23
        DataField = 'bitola'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxLiga_fio: TGroupBox
      Left = 92
      Top = 93
      Width = 45
      Height = 36
      Caption = 'LIGA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      object edtLiga_fio: TDBEditTexto
        Left = 2
        Top = 10
        Width = 39
        Height = 23
        DataField = 'liga'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object gbxVolta_fio: TGroupBox
      Left = 142
      Top = 93
      Width = 49
      Height = 36
      Caption = 'VOLTA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      object edtVolta_fio: TDBEditNumero
        Left = 2
        Top = 10
        Width = 43
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = False
        TipoMascara = tmGERAL
        NrDecimal = 0
        Decimais = False
        Negativo = False
        Tamanho = 9
        DataField = 'nrvoltas'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
      end
    end
    object gbxqtidadeporgrama_fio: TGroupBox
      Left = 196
      Top = 92
      Width = 113
      Height = 36
      Caption = 'QTD (g / pe'#231'a)'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      object edtqtidadeporgrama_fio: TDBEditNumero
        Left = 3
        Top = 10
        Width = 107
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = True
        TipoMascara = tmGERAL
        NrDecimal = 8
        Decimais = True
        Negativo = False
        Tamanho = 15
        DataField = 'gramasporpeca'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
      end
    end
    object gbxResistividade_fio: TGroupBox
      Left = 313
      Top = 92
      Width = 89
      Height = 36
      Caption = 'OHMs / m'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      object edtResistividade_fio: TDBEditNumero
        Left = 2
        Top = 10
        Width = 84
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = True
        TipoMascara = tmGERAL
        NrDecimal = 3
        Decimais = True
        Negativo = False
        Tamanho = 8
        DataField = 'resistividade'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
      end
    end
    object gbxTolerancia_fio: TGroupBox
      Left = 405
      Top = 92
      Width = 57
      Height = 36
      Caption = 'TOL. %'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      object edtTolerancia_fio: TDBEditNumero
        Left = 2
        Top = 10
        Width = 52
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Mascara = False
        TipoMascara = tmGERAL
        NrDecimal = 0
        Decimais = False
        Negativo = False
        Tamanho = 9
        DataField = 'tolerancia'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
      end
    end
    object gbxComponente: TGroupBox
      Left = 8
      Top = 47
      Width = 213
      Height = 36
      Caption = 'COMPONENTE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object dtxCodigoComponente: TtecDBText
        Left = 4
        Top = 11
        Width = 205
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'componente'
        DataSource = dtmCadastroProdutos.dsrProdutoCompostoFios
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
    end
  end
end
