inherited frmCadastroProdutosImportados: TfrmCadastroProdutosImportados
  Left = 545
  Top = 258
  ActiveControl = fraConsultaCodigoProduto
  Caption = 'Cadastro de Produtos Importados'
  ClientHeight = 123
  ClientWidth = 541
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Top = 44
    TabOrder = 5
  end
  inherited pnlTopMenu: TPanel
    Width = 541
    TabOrder = 6
    inherited tblBarra: TToolBar
      Width = 316
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
  end
  object gbxProduto: TGroupBox
    Left = 0
    Top = 42
    Width = 537
    Height = 36
    Caption = 'PRODUTO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    inline fraConsultaCodigoProduto: TfraConsultaCodigo
      Left = 1
      Top = 10
      Width = 534
      Height = 23
      HorzScrollBar.Range = 533
      VertScrollBar.Range = 23
      AutoScroll = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      inherited sbnProcura: TSpeedButton
        Left = 136
      end
      inherited dtxDescricao: TtecDBText
        Left = 160
        Width = 373
        DataField = 'descricaolc'
        DataSource = dtmCadastroNotasFiscais.dsrProcuraProdutoNotaFiscal
      end
      inherited edfCodigo: TtecDBFindLookup
        Left = 2
        Width = 132
        DataaFieldInterno = 'produto'
        DataaFieldVisual = 'produtovisual'
        DataField = 'produtodigitado'
        DataSource = dtmCadastroNotasFiscais.dsrProdutosImportados
        MaxLength = 30
        OnFound = nil
        LookupaFieldinterno = 'produto'
        LookupaFieldVisual = 'produtovisual'
        LookupField = 'produtovisual'
        LookupSource = dtmCadastroNotasFiscais.dsrProcuraProdutoNotaFiscal
        LookupQueryParameter = 'produtovisual'
        Parameter = ' '
        ActiveSetControls = False
        DenyInsert = False
        NoSetControls = <>
        SetControls = <>
        LookupParameter = 'produtovisual'
      end
    end
  end
  object gbxAdicao: TGroupBox
    Left = 0
    Top = 82
    Width = 51
    Height = 36
    Caption = 'ADI'#199#195'O'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    object flkAdicao: TtecDBFindLookup
      Left = 2
      Top = 10
      Width = 46
      Height = 23
      Alignment = taLeftJustify
      DataField = 'numeroadicao'
      DataSource = dtmCadastroNotasFiscais.dsrProdutosImportados
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 3
      Maximo = 0
      Minimo = 37353
      Adicional = 0
      Opcional = True
      ParentFont = False
      TabOrder = 0
      PermitirZero = False
      PermitirNulo = False
      Operacao = opATRIBUICAO
      LookupField = 'numero'
      LookupSource = dtmCadastroNotasFiscais.dsrProcuraAdicoesImportacao
      LookupQueryParameter = 'numero'
      Parameter = ' '
      ActiveSetControls = False
      DenyInsert = False
      NoSetControls = <>
      SetControls = <>
      LookupParameter = 'numero'
    end
  end
  object gbxQuantidade: TGroupBox
    Left = 56
    Top = 82
    Width = 86
    Height = 36
    Caption = 'QUANTIDADE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    object edtQuantidade: TDBEditNumero
      Left = 2
      Top = 10
      Width = 81
      Height = 24
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = False
      TipoMascara = tmQUANTIDADE
      NrDecimal = 0
      Decimais = False
      Negativo = False
      Tamanho = 0
      DataField = 'quantidade'
      DataSource = dtmCadastroNotasFiscais.dsrProdutosImportados
    end
  end
  object gbxValorTotal: TGroupBox
    Left = 146
    Top = 82
    Width = 128
    Height = 36
    Caption = 'VALOR TOTAL(ORIGINAL)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    object edtValorTotal: TDBEditNumero
      Left = 2
      Top = 10
      Width = 123
      Height = 24
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      OnKeyDown = edtValorTotalKeyDown
      Mascara = False
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 14
      DataField = 'valor'
      DataSource = dtmCadastroNotasFiscais.dsrProdutosImportados
    end
  end
  object gbxIPI: TGroupBox
    Left = 280
    Top = 82
    Width = 51
    Height = 36
    Caption = '%IPI'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 4
    object edtIPI: TDBEditNumero
      Left = 2
      Top = 10
      Width = 46
      Height = 24
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 5
      ParentFont = False
      TabOrder = 0
      Mascara = False
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 5
      DataField = 'aliquotaipi'
      DataSource = dtmCadastroNotasFiscais.dsrProdutosImportados
    end
  end
end
