inherited frmCadastroImpostosNotaFiscal: TfrmCadastroImpostosNotaFiscal
  Left = 480
  Top = 247
  ActiveControl = cmbTipo
  Caption = 'Cadastro de Impostos'
  ClientHeight = 246
  ClientWidth = 314
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Width = 282
    inherited bvlBotoesEd: TBevel
      Left = 201
      Height = 35
    end
  end
  inherited pnlTopMenu: TPanel
    Width = 306
    TabOrder = 2
    inherited tblBarra: TToolBar
      Width = 81
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
  end
  object pnlFundoJanela: TPanel
    Left = 0
    Top = 40
    Width = 306
    Height = 206
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object gbxImpostos: TGroupBox
      Left = 0
      Top = 0
      Width = 306
      Height = 206
      Align = alClient
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object gbxTipoImposto: TGroupBox
        Left = 6
        Top = 6
        Width = 72
        Height = 36
        Caption = 'TIPO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object cmbTipo: TtecDBComboBox
          Left = 2
          Top = 10
          Width = 66
          Height = 24
          DataField = 'tipo'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ItemHeight = 16
          Items.Strings = (
            'ICMS'
            'IPI'
            'ISS')
          ParentFont = False
          TabOrder = 0
        end
      end
      object gbxBaseCalculo: TGroupBox
        Left = 84
        Top = 6
        Width = 105
        Height = 36
        Caption = 'BASE DE C'#193'LCULO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object edtValorBase: TDBEditNumero
          Left = 2
          Top = 10
          Width = 100
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Text = '999.999.999,99'
          Mascara = True
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 12
          DataField = 'base'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
        end
      end
      object gbxAliquota: TGroupBox
        Left = 194
        Top = 6
        Width = 75
        Height = 36
        Caption = 'AL'#205'QUOTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object lblPercentual: TLabel
          Left = 58
          Top = 18
          Width = 12
          Height = 16
          Caption = '%'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
        end
        object edtAliquota: TDBEditNumero
          Left = 2
          Top = 10
          Width = 50
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Text = '999,99'
          Mascara = True
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 6
          DataField = 'aliquota'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
        end
      end
      object gbxValorImposto: TGroupBox
        Left = 84
        Top = 55
        Width = 105
        Height = 36
        Caption = 'VALOR IMPOSTO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object edtValor: TDBEditNumero
          Left = 2
          Top = 10
          Width = 100
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Text = '999.999.999,99'
          Mascara = True
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 12
          DataField = 'valor'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
        end
      end
      object gbxIsentas: TGroupBox
        Left = 84
        Top = 107
        Width = 105
        Height = 36
        Caption = 'ISENTAS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object edtIsentos: TDBEditNumero
          Left = 2
          Top = 10
          Width = 100
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Text = '999.999.999,99'
          Mascara = True
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 12
          DataField = 'isentas'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
        end
      end
      object gbxOutras: TGroupBox
        Left = 84
        Top = 159
        Width = 105
        Height = 36
        Caption = 'OUTRAS OPERA'#199#213'ES'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        object edtOutros: TDBEditNumero
          Left = 2
          Top = 10
          Width = 100
          Height = 24
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Text = '999.999.999,99'
          Mascara = True
          TipoMascara = tmGERAL
          NrDecimal = 2
          Decimais = True
          Negativo = False
          Tamanho = 12
          DataField = 'outras'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
        end
      end
      object gbxTotal: TGroupBox
        Left = 194
        Top = 159
        Width = 105
        Height = 36
        Caption = 'TOTAL'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        object dtxTotalImposto: TtecDBText
          Left = 2
          Top = 10
          Width = 100
          Height = 24
          TabStop = False
          Color = clBtnFace
          DataField = 'Total'
          DataSource = dtmCadastroNotasFiscais.dsrCalculosNotasPag
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
        end
      end
    end
  end
end
