inherited frmrelatorioestoqueicmsstarecolher: Tfrmrelatorioestoqueicmsstarecolher
  Left = 635
  Top = 343
  ActiveControl = fraConsultaFilial
  Caption = 'Relat'#243'rio Estoque ICMS ST a recolher'
  ClientHeight = 200
  ClientWidth = 516
  FormStyle = fsMDIChild
  Visible = True
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TToolBar
    Width = 516
  end
  inherited pnlFundoJanela: TPanel
    Top = 41
    Width = 516
    Height = 159
    object gbxPeriodo: TGroupBox
      Left = 6
      Top = 53
      Width = 80
      Height = 37
      Caption = 'ESTOQUE EM'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object edtDataInventario: TEditData
        Left = 2
        Top = 10
        Width = 75
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 0
        Minimo = 37353
        Maximo = 0
      end
    end
    object gbxFilial: TGroupBox
      Left = 6
      Top = 6
      Width = 502
      Height = 36
      Caption = 'FILIAL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      inline fraConsultaFilial: TfraConsultaCodigo
        Left = 3
        Top = 10
        Width = 498
        Height = 24
        HorzScrollBar.Range = 496
        VertScrollBar.Range = 23
        AutoScroll = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        inherited dtxDescricao: TtecDBText
          Left = 87
          Top = 1
          DataField = 'nome'
          DataSource = fraConsultaFilial.dsrProcuraFiliais
        end
        inherited edfCodigo: TtecDBFindLookup
          Left = -1
          Top = 1
          DataField = 'codigo'
          DataSource = fraConsultaFilial.dsrProcuraFiliais
          Group = 'filial'
          MaxLength = 4
          OnFound = nil
          Operacao = opPESQUISA
          Parameter = 'codigo'
          ActiveSetControls = False
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
        end
      end
    end
    object GroupBox1: TGroupBox
      Left = 97
      Top = 53
      Width = 127
      Height = 94
      Caption = 'NUMERA'#199#195'O'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      object gbxLivro: TGroupBox
        Left = 6
        Top = 12
        Width = 55
        Height = 36
        Caption = 'LIVRO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object edtLivro: TEditNumero
          Left = 2
          Top = 10
          Width = 50
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = False
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 0
          Decimais = False
          Negativo = False
          Tamanho = 4
        end
      end
      object gbxPagina: TGroupBox
        Left = 66
        Top = 12
        Width = 55
        Height = 36
        Caption = 'P'#193'GINA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object edtPagina: TEditNumero
          Left = 2
          Top = 10
          Width = 50
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = False
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 0
          Decimais = False
          Negativo = False
          Tamanho = 9
        end
      end
      object gbxMaximo: TGroupBox
        Left = 66
        Top = 52
        Width = 55
        Height = 36
        Caption = 'M'#193'XIMO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object edtMaximo: TEditNumero
          Left = 2
          Top = 10
          Width = 50
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = -1
          ParentFont = False
          TabOrder = 0
          Mascara = False
          Alignment = taLeftJustify
          TipoMascara = tmGERAL
          NrDecimal = 0
          Decimais = False
          Negativo = False
          Tamanho = 9
        end
      end
    end
  end
end
