library ecfelgin;

uses
  SysUtils,
  Classes,
  ctelgin in '../ctelgin.pas',
  bbelgin in 'bbelgin.pas';

{$SONAME 'tececfelgin.so'}
{$SOPREFIX 'tec'}
{$SOVERSION '1.0'}

exports
    Elgin_AlteraSimboloMoeda 		     name 'Elgin_AlteraSimboloMoeda',
    Elgin_ProgramaAliquota 		     name 'Elgin_ProgramaAliquota',
    Elgin_ProgramaHorarioVerao 		     name 'Elgin_ProgramaHorarioVerao',
    Elgin_NomeiaDepartamento 		     name 'Elgin_NomeiaDepartamento',
    Elgin_NomeiaTotalizadorNaoSujeitoIcms    name 'Elgin_NomeiaTotalizadorNaoSujeitoIcms',
    Elgin_ProgramaArredondamento 	     name 'Elgin_ProgramaArredondamento',
    Elgin_ProgramaTruncamento 		     name 'Elgin_ProgramaTruncamento',
    Elgin_LinhasEntreCupons 		     name 'Elgin_LinhasEntreCupons',
    Elgin_EspacoEntreLinhas 		     name 'Elgin_EspacoEntreLinhas',
    Elgin_AbreCupom 			     name 'Elgin_AbreCupom',
    Elgin_VendeItem 			     name 'Elgin_VendeItem',
    Elgin_VendeItemDepartamento              name 'Elgin_VendeItemDepartamento',
    Elgin_CancelaItemAnterior                name 'Elgin_CancelaItemAnterior',
    Elgin_CancelaItemGenerico                name 'Elgin_CancelaItemGenerico',
    Elgin_CancelaCupom                       name 'Elgin_CancelaCupom',
    Elgin_FechaCupomResumido                 name 'Elgin_FechaCupomResumido',
    Elgin_FechaCupom                         name 'Elgin_FechaCupom',
    Elgin_ResetaImpressora                   name 'Elgin_ResetaImpressora',
    Elgin_IniciaFechamentoCupom              name 'Elgin_IniciaFechamentoCupom',
    Elgin_EfetuaFormaPagamento               name 'Elgin_EfetuaFormaPagamento',
    Elgin_TerminaFechamentoCupom             name 'Elgin_TerminaFechamentoCupom',
    Elgin_UsaUnidadeMedida                   name 'Elgin_UsaUnidadeMedida',
    Elgin_AumentaDescricaoItem               name 'Elgin_AumentaDescricaoItem',
    Elgin_LeituraX                           name 'Elgin_LeituraX',
    Elgin_ReducaoZ                           name 'Elgin_ReducaoZ',
    Elgin_RelatorioGerencial                 name 'Elgin_RelatorioGerencial',
    Elgin_FechaRelatorioGerencial            name 'Elgin_FechaRelatorioGerencial',
    Elgin_LeituraMemoriaFiscalData           name 'Elgin_LeituraMemoriaFiscalData',
    Elgin_LeituraMemoriaFiscalReducao        name 'Elgin_LeituraMemoriaFiscalReducao',
    Elgin_LeituraMemoriaFiscalSerialData     name 'Elgin_LeituraMemoriaFiscalSerialData',
    Elgin_LeituraMemoriaFiscalSerialReducao  name 'Elgin_LeituraMemoriaFiscalSerialReducao',
    Elgin_RecebimentoNaoFiscal               name 'Elgin_RecebimentoNaoFiscal',
    Elgin_AbreComprovanteNaoFiscalVinculado  name 'Elgin_AbreComprovanteNaoFiscalVinculado',
    Elgin_UsaComprovanteNaoFiscalVinculado   name 'Elgin_UsaComprovanteNaoFiscalVinculado',
    Elgin_FechaComprovanteNaoFiscalVinculado name 'Elgin_FechaComprovanteNaoFiscalVinculado',
    Elgin_Sangria                            name 'Elgin_Sangria',
    Elgin_Suprimento                         name 'Elgin_Suprimento',
    Elgin_NumeroSerie                        name 'Elgin_NumeroSerie',
    Elgin_SubTotal                           name 'Elgin_SubTotal',
    Elgin_NumeroCupom                        name 'Elgin_NumeroCupom',
    Elgin_LeituraXSerial                     name 'Elgin_LeituraXSerial',
    Elgin_VersaoFirmware                     name 'Elgin_VersaoFirmware',
    Elgin_CGC_IE                             name 'Elgin_CGC_IE',
    Elgin_GrandeTotal                        name 'Elgin_GrandeTotal',
    Elgin_Cancelamentos                      name 'Elgin_Cancelamentos',
    Elgin_Descontos                          name 'Elgin_Descontos',
    Elgin_NumeroOperacoesNaoFiscais          name 'Elgin_NumeroOperacoesNaoFiscais',
    Elgin_NumeroCuponsCancelados             name 'Elgin_NumeroCuponsCancelados',
    Elgin_NumeroIntervencoes                 name 'Elgin_NumeroIntervencoes',
    Elgin_NumeroReducoes                     name 'Elgin_NumeroReducoes',
    Elgin_NumeroSubstituicoesProprietario    name 'Elgin_NumeroSubstituicoesProprietario',
    Elgin_UltimoItemVendido                  name 'Elgin_UltimoItemVendido',
    Elgin_ClicheProprietario                 name 'Elgin_ClicheProprietario',
    Elgin_NumeroCaixa                        name 'Elgin_NumeroCaixa',
    Elgin_NumeroLoja                         name 'Elgin_NumeroLoja',
    Elgin_SimboloMoeda                       name 'Elgin_SimboloMoeda',
    Elgin_MinutosLigada                      name 'Elgin_MinutosLigada',
    Elgin_MinutosImprimindo                  name 'Elgin_MinutosImprimindo',
    Elgin_VerificaModoOperacao               name 'Elgin_VerificaModoOperacao',
    Elgin_VerificaEpromConectada             name 'Elgin_VerificaEpromConectada',
    Elgin_FlagsFiscais                       name 'Elgin_FlagsFiscais',
    Elgin_ValorPagoUltimoCupom               name 'Elgin_ValorPagoUltimoCupom',
    Elgin_DataHoraImpressora                 name 'Elgin_DataHoraImpressora',
    Elgin_ContadoresTotalizadoresNaoFiscais  name 'Elgin_ContadoresTotalizadoresNaoFiscais',
    Elgin_VerificaTotalizadoresNaoFiscais    name 'Elgin_VerificaTotalizadoresNaoFiscais',
    Elgin_DataHoraReducao                    name 'Elgin_DataHoraReducao',
    Elgin_DataMovimento                      name 'Elgin_DataMovimento',
    Elgin_VerificaTruncamento                name 'Elgin_VerificaTruncamento',
    Elgin_Acrescimos                         name 'Elgin_Acrescimos',
    Elgin_ContadorBilhetePassagem            name 'Elgin_ContadorBilhetePassagem',
    Elgin_VerificaRecebimentoNaoFiscal       name 'Elgin_VerificaRecebimentoNaoFiscal',
    Elgin_VerificaDepartamentos              name 'Elgin_VerificaDepartamentos',
    Elgin_VerificaTipoImpressora             name 'Elgin_VerificaTipoImpressora',
    Elgin_VerificaTotalizadoresParciais      name 'Elgin_VerificaTotalizadoresParciais',
    Elgin_RetornoAliquotas                   name 'Elgin_RetornoAliquotas',
    Elgin_DadosUltimaReducao                 name 'Elgin_DadosUltimaReducao',
    Elgin_MonitoramentoPapel                 name 'Elgin_MonitoramentoPapel',
    Elgin_VerificaIndiceAliquotasIss         name 'Elgin_VerificaIndiceAliquotasIss',
    Elgin_ValorFormaPagamento                name 'Elgin_ValorFormaPagamento',
    Elgin_Autenticacao                       name 'Elgin_Autenticacao',
    Elgin_ProgramaCaracterAutenticacao       name 'Elgin_ProgramaCaracterAutenticacao',
    Elgin_AcionaGaveta                       name 'Elgin_AcionaGaveta',
    Elgin_VerificaEstadoGaveta               name 'Elgin_VerificaEstadoGaveta',
    Elgin_ProgramaMoedaSingular              name 'Elgin_ProgramaMoedaSingular',
    Elgin_ProgramaMoedaPlural                name 'Elgin_ProgramaMoedaPlural',
    Elgin_CancelaImpressaoCheque             name 'Elgin_CancelaImpressaoCheque',
    Elgin_VerificaStatusCheque               name 'Elgin_VerificaStatusCheque',
    Elgin_ImprimeCheque                      name 'Elgin_ImprimeCheque',
    Elgin_AbrePortaSerial                    name 'Elgin_AbrePortaSerial',
    Elgin_FechaPortaSerial                   name 'Elgin_FechaPortaSerial',
    Elgin_VerificaFormaPagamento             name 'Elgin_VerificaFormaPagamento',
    Elgin_ProgramaFormasPagamento            name 'Elgin_ProgramaFormasPagamento',
    Elgin_ContadorSequencial                 name 'Elgin_ContadorSequencial',
    Elgin_ContadoresTotalizadoresNaoSujeitos name 'Elgin_ContadoresTotalizadoresNaoSujeitos',
    Elgin_ImprimeChequeBR400                 name 'Elgin_ImprimeChequeBR400',
    Elgin_LeituraCheque                      name 'Elgin_LeituraCheque';

procedure SignalHandler(Reason: Integer);
begin
  if Reason = 0 then
    UnhookSignal(RTL_SIGDEFAULT);
end;

begin
  HookSignal(RTL_SIGDEFAULT);
  DllProc := @SignalHandler;
end.
