inherited frmCadastroProdutosClientesPedidosSaidas: TfrmCadastroProdutosClientesPedidosSaidas
  Left = 236
  Top = 343
  ActiveControl = edtProdutoCliente
  Caption = 'Cadastro de Produtos do Cliente'
  ClientWidth = 508
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    TabOrder = 6
  end
  inherited pnlTopMenu: TPanel
    Width = 508
    TabOrder = 7
    inherited tblBarra: TToolBar
      Width = 283
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
    inherited tblBarraCadastro: TToolBar
      inherited sbnIncluir: TSpeedButton
        Visible = False
      end
      inherited sbnExcluir: TSpeedButton
        Visible = False
      end
    end
  end
  object gbxProdutoCliente: TGroupBox
    Left = 5
    Top = 129
    Width = 188
    Height = 40
    Caption = 'PRODUTO NO CLIENTE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    object edtProdutoCliente: TDBEditTexto
      Left = 5
      Top = 12
      Width = 178
      Height = 24
      DataField = 'produto_cliente'
      DataSource = dsrProdutosClientes
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 12
      ParentFont = False
      TabOrder = 0
      CharCasenoDefault = False
    end
  end
  object gbxProduto: TGroupBox
    Left = 5
    Top = 89
    Width = 500
    Height = 40
    Caption = 'PRODUTO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    object dtxCodigoProduto: TtecDBText
      Left = 3
      Top = 12
      Width = 182
      Height = 24
      TabStop = False
      Color = clBtnFace
      DataField = 'produtovisual'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
    object dtxDescricaoProduto: TtecDBText
      Left = 187
      Top = 12
      Width = 310
      Height = 24
      TabStop = False
      Color = clBtnFace
      DataField = 'descricao'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
    end
  end
  object gbxPN: TGroupBox
    Left = 444
    Top = 129
    Width = 61
    Height = 40
    Caption = 'PN'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    object edtPN: TDBEditNumero
      Left = 5
      Top = 12
      Width = 50
      Height = 24
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 6
      ParentFont = False
      TabOrder = 0
      Mascara = True
      Alignment = taLeftJustify
      TipoMascara = tmGERAL
      NrDecimal = 0
      Decimais = False
      Negativo = False
      Tamanho = 6
      DataField = 'pn'
      DataSource = dsrProdutosClientes
    end
  end
  object gbxOrigem: TGroupBox
    Left = 385
    Top = 129
    Width = 61
    Height = 40
    Caption = 'ORIGEM'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 4
    object edtOrigem: TDBEditTexto
      Left = 5
      Top = 12
      Width = 51
      Height = 24
      DataField = 'origem'
      DataSource = dsrProdutosClientes
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 1
      ParentFont = False
      TabOrder = 0
      CharCasenoDefault = False
    end
  end
  object gbxCliente: TGroupBox
    Left = 5
    Top = 48
    Width = 500
    Height = 40
    Caption = 'CLIENTE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object dtxCodigoCliente: TtecDBText
      Left = 3
      Top = 12
      Width = 70
      Height = 24
      TabStop = False
      Color = clBtnFace
      DataField = 'cliente'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
    object dtxNomeCliente: TtecDBText
      Left = 73
      Top = 12
      Width = 424
      Height = 24
      TabStop = False
      Color = clBtnFace
      DataField = 'nome'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
    end
  end
  object gbxFinalidade: TGroupBox
    Left = 191
    Top = 129
    Width = 196
    Height = 40
    Caption = 'FINALIDADE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    object edtFinalidade: TDBEditTexto
      Left = 5
      Top = 12
      Width = 186
      Height = 24
      DataField = 'finalidade'
      DataSource = dsrProdutosClientes
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      TabOrder = 0
      CharCasenoDefault = False
    end
  end
  object dsrProdutosClientes: TtecDataSource
    Left = 432
    Top = 32
  end
end
