object fraCMC7: TfraCMC7
  Left = 0
  Top = 0
  Width = 328
  Height = 139
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -11
  Font.Name = 'Helvetica'
  Font.Pitch = fpVariable
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object gbxCMC7: TGroupBox
    Left = 0
    Top = 0
    Width = 328
    Height = 139
    Align = alClient
    Caption = 'IDENTIFICAC'#195'O DO CHEQUE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'Helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object gbxLeitura: TGroupBox
      Left = 7
      Top = 54
      Width = 314
      Height = 36
      Caption = 'C'#211'DIGO CMC-7'
      TabOrder = 0
      object edtCMC7: TEdit
        Left = 2
        Top = 10
        Width = 309
        Height = 24
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 34
        ParentFont = False
        TabOrder = 0
        OnExit = edtCMC7Exit
      end
    end
    object gbxBanco: TGroupBox
      Left = 7
      Top = 13
      Width = 44
      Height = 36
      Caption = 'BANCO'
      TabOrder = 2
      object edtBanco: TEditNumero
        Left = 2
        Top = 10
        Width = 39
        Height = 24
        TabStop = False
        CharCase = ecUpperCase
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Mascara = False
        Alignment = taCenter
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = False
        Negativo = False
        Tamanho = 3
      end
    end
    object gbxLeituraManual: TGroupBox
      Left = 7
      Top = 96
      Width = 314
      Height = 36
      Caption = 'DIGITA'#199#195'O MANUAL'
      TabOrder = 1
      object edtManual1: TEdit
        Left = 2
        Top = 10
        Width = 85
        Height = 24
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 8
        ParentFont = False
        TabOrder = 0
        OnExit = edtManual1Exit
      end
      object edtManual2: TEdit
        Left = 88
        Top = 10
        Width = 100
        Height = 24
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 1
        OnExit = edtManual2Exit
      end
      object edtManual3: TEdit
        Left = 189
        Top = 10
        Width = 122
        Height = 24
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 12
        ParentFont = False
        TabOrder = 2
        OnExit = edtManual3Exit
      end
    end
    object gbxAgencia: TGroupBox
      Left = 68
      Top = 13
      Width = 55
      Height = 36
      Caption = 'AG'#202'NCIA'
      TabOrder = 3
      object edtAgencia: TEditNumero
        Left = 2
        Top = 10
        Width = 50
        Height = 24
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Mascara = False
        Alignment = taCenter
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = False
        Negativo = False
        Tamanho = 4
      end
    end
    object gbxNrCheque: TGroupBox
      Left = 254
      Top = 13
      Width = 67
      Height = 36
      Caption = 'N'#186' CHEQUE'
      TabOrder = 5
      object edtCheque: TEditNumero
        Left = 2
        Top = 10
        Width = 62
        Height = 24
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Mascara = False
        Alignment = taCenter
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = False
        Negativo = False
        Tamanho = 6
      end
    end
    object gbxConta: TGroupBox
      Left = 142
      Top = 13
      Width = 94
      Height = 36
      Caption = 'CONTA'
      TabOrder = 4
      object edtConta: TEditNumero
        Left = 2
        Top = 10
        Width = 89
        Height = 24
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Mascara = False
        Alignment = taCenter
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = False
        Negativo = False
        Tamanho = 10
      end
    end
  end
end
