object fraComissao: TfraComissao
  Left = 0
  Top = 0
  Width = 145
  Height = 81
  HorzScrollBar.Range = 143
  VertScrollBar.Range = 74
  AutoScroll = False
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'helvetica'
  Font.Pitch = fpVariable
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object gbxComissao: TGroupBox
    Left = 0
    Top = -1
    Width = 143
    Height = 75
    Caption = 'COMISS'#195'O'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object lblComissao: TLabel
      Left = 76
      Top = 32
      Width = 62
      Height = 12
      Alignment = taRightJustify
      Caption = 'PERCENTUAL'
      FocusControl = dtxComissao
    end
    object dtxComissao: TDBEditNumero
      Left = 71
      Top = 46
      Width = 68
      Height = 24
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 1
      OnExit = dtxComissaoExit
      Mascara = True
      Alignment = taLeftJustify
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = True
      Negativo = False
      Tamanho = 3
      DataField = 'comissao'
    end
    object rgpTipoComissao: TtecDBRadioGroup
      Left = 3
      Top = 17
      Width = 63
      Height = 55
      Caption = 'TIPO'
      TabOrder = 0
      TabStop = False
      DataField = 'tipocomissao'
      OnChange = rgpTipoComissaoChange
      object rbnPercentual: TtecRadioButton
        Left = 13
        Top = 14
        Width = 37
        Height = 17
        Caption = '%'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        OnKeyDown = rbnPercentualKeyDown
        Value = '%'
      end
      object rbnValor: TtecRadioButton
        Left = 13
        Top = 32
        Width = 37
        Height = 17
        Caption = 'R$'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Value = 'V'
      end
    end
  end
end
