object fraEndereco: TfraEndereco
  Left = 0
  Top = 0
  Width = 429
  Height = 152
  HorzScrollBar.Visible = False
  VertScrollBar.Visible = False
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'helvetica'
  Font.Pitch = fpVariable
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object gbxEndereco: TGroupBox
    Left = 0
    Top = 0
    Width = 429
    Height = 152
    Align = alClient
    Caption = 'ENDERE'#199'O'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object pnlNumero: TPanel
      Left = 2
      Top = 54
      Width = 425
      Height = 23
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 1
      object edtNumeroEndereco: TDBEditTexto
        Left = 1
        Top = 0
        Width = 80
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
      object edtComplemento: TDBEditTexto
        Left = 83
        Top = 0
        Width = 338
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        TabOrder = 1
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object pnlBairro: TPanel
      Left = 2
      Top = 87
      Width = 425
      Height = 25
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 2
      object edtBairro: TtecDoubleDBEdit
        Left = 1
        Top = 0
        Width = 420
        Height = 23
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
    object pnlCidade: TPanel
      Left = 2
      Top = 122
      Width = 425
      Height = 23
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 3
      object edtCEP: TDBEditCep
        Left = 1
        Top = -1
        Width = 80
        Height = 23
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 8
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Tamanho = 8
        Decimais = False
        Negativo = False
      end
      object edtCidade: TtecDoubleDBEdit
        Left = 84
        Top = -1
        Width = 305
        Height = 23
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
      end
      object edtEstado: TDBEditTexto
        Left = 391
        Top = -1
        Width = 31
        Height = 23
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        CharCasenoDefault = False
        Alignment = taLeftJustify
      end
    end
    object pnlRua: TPanel
      Left = 2
      Top = 14
      Width = 425
      Height = 30
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 0
      object mmoRua: TtecDBMemo
        Left = 0
        Top = 0
        Width = 421
        Height = 29
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = False
        TabOrder = 0
      end
    end
    object pnllblCidade: TPanel
      Left = 2
      Top = 112
      Width = 425
      Height = 10
      Align = alTop
      BevelOuter = bvNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      object lblCEP_: TLabel
        Left = 5
        Top = -1
        Width = 19
        Height = 12
        Alignment = taRightJustify
        Caption = 'CEP'
        FocusControl = edtCEP
      end
      object lblCidade_: TLabel
        Left = 87
        Top = -1
        Width = 36
        Height = 12
        Alignment = taRightJustify
        Caption = 'CIDADE'
        FocusControl = edtCidade
      end
      object lblUF_: TLabel
        Left = 393
        Top = -1
        Width = 13
        Height = 12
        Alignment = taRightJustify
        Caption = 'UF'
        FocusControl = edtEstado
      end
    end
    object pnllblBairro: TPanel
      Left = 2
      Top = 77
      Width = 425
      Height = 10
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 5
      object lblBairro_: TLabel
        Left = 6
        Top = 0
        Width = 36
        Height = 12
        Alignment = taRightJustify
        Caption = 'BAIRRO'
        FocusControl = edtBairro
      end
    end
    object pnllblNumero: TPanel
      Left = 2
      Top = 44
      Width = 425
      Height = 10
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 4
      object lblenderecocliente_numero: TLabel
        Left = 3
        Top = -1
        Width = 40
        Height = 12
        Alignment = taRightJustify
        Caption = 'N'#218'MERO'
        FocusControl = edtNumeroEndereco
      end
      object lblenderecocliente_complemento: TLabel
        Left = 86
        Top = -1
        Width = 70
        Height = 12
        Alignment = taRightJustify
        Caption = 'COMPLEMENTO'
        FocusControl = edtComplemento
      end
    end
  end
end
