object fraIntervaloDatas: TfraIntervaloDatas
  Left = 0
  Top = 0
  Width = 162
  Height = 36
  Constraints.MaxHeight = 36
  Constraints.MaxWidth = 162
  Constraints.MinHeight = 36
  Constraints.MinWidth = 162
  TabOrder = 0
  object gbxPeriodo: TGroupBox
    Left = 0
    Top = 0
    Width = 162
    Height = 36
    Align = alClient
    Caption = 'INTERVALO DE DATAS'
    Constraints.MaxHeight = 36
    Constraints.MaxWidth = 162
    Constraints.MinHeight = 36
    Constraints.MinWidth = 162
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object lblDataFinal: TLabel
      Left = 77
      Top = 15
      Width = 7
      Height = 15
      Caption = 'a'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
    end
    object edtDataInicial: TEditData
      Left = 2
      Top = 10
      Width = 70
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      TabOrder = 0
      Minimo = 37353
      Maximo = 0
    end
    object edtDataFinal: TEditData
      Left = 88
      Top = 10
      Width = 70
      Height = 23
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      TabOrder = 1
      Minimo = 37353
      Maximo = 0
    end
  end
end
