object fraRegistroOperacoes: TfraRegistroOperacoes
  Left = 0
  Top = 0
  Width = 194
  Height = 177
  TabOrder = 0
  object gbxRegistrodasOperacoes: TGroupBox
    Left = 0
    Top = 0
    Width = 194
    Height = 177
    Align = alClient
    Caption = 'LOG DAS OPERA'#199#213'ES'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    object gbxRegistroInclusao: TGroupBox
      Left = 2
      Top = 16
      Width = 190
      Height = 59
      Align = alTop
      BiDiMode = bdLeftToRight
      Caption = 'INCLUS'#195'O'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -9
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentBiDiMode = False
      ParentFont = False
      TabOrder = 0
      object sttDataInclusao: TStaticText
        Left = 2
        Top = 13
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Data/Hora'
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object sttUsuarioInclusao: TStaticText
        Left = 2
        Top = 34
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkTile
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Usu'#225'rio'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object dtxDataInclusao: TtecDBText
        Left = 59
        Top = 15
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'DataInclusao'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        Alignment = taLeftJustify
      end
      object dtxUsuarioInclusao: TtecDBText
        Left = 59
        Top = 36
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'NomeUsuarioInclusao'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 3
        Alignment = taLeftJustify
      end
    end
    object gbxRegistroAlteracao: TGroupBox
      Left = 2
      Top = 75
      Width = 190
      Height = 101
      Align = alTop
      Caption = 'ALTERA'#199#195'O'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -9
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      object sttDataAlteracao: TStaticText
        Left = 2
        Top = 13
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Data/Hora'
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object dtxDataAlteracao: TtecDBText
        Left = 59
        Top = 15
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'DataAlteracao'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Alignment = taLeftJustify
      end
      object sttUsuarioAlteracao: TStaticText
        Left = 2
        Top = 34
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkTile
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Usu'#225'rio'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object dtxUsuarioAlteracao: TtecDBText
        Left = 59
        Top = 36
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'NomeUsuarioAlteracao'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 3
        Alignment = taLeftJustify
      end
      object sttOperacao: TStaticText
        Left = 2
        Top = 55
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkTile
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Opera'#231#227'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object dtxOperacao: TtecDBText
        Left = 59
        Top = 57
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'Operacao'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        Alignment = taLeftJustify
      end
      object sttTabela: TStaticText
        Left = 2
        Top = 76
        Width = 186
        Height = 21
        Align = alTop
        AutoSize = False
        BevelKind = bkTile
        BevelOuter = bvSpace
        BorderStyle = sbsSingle
        Caption = 'Tabela'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
      end
      object dtxTabela: TtecDBText
        Left = 59
        Top = 78
        Width = 126
        Height = 18
        TabStop = False
        BevelOuter = bvSpace
        BevelKind = bkSoft
        BorderStyle = bsNone
        Color = 14540253
        DataField = 'tabela'
        DataSource = dsrRegistrodasOperacaoes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
        Alignment = taLeftJustify
      end
    end
  end
  object dsrRegistrodasOperacaoes: TtecDataSource
    Left = 79
    Top = 61
  end
end
