object fraTelefone: TfraTelefone
  Left = 0
  Top = 0
  Width = 152
  Height = 51
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'helvetica'
  Font.Pitch = fpVariable
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object gbxFone: TGroupBox
    Left = 0
    Top = 0
    Width = 152
    Height = 51
    Align = alClient
    Caption = 'TELEFONE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object lblDDD: TLabel
      Left = 3
      Top = 12
      Width = 21
      Height = 12
      Caption = 'DDD'
    end
    object lblNumero: TLabel
      Left = 47
      Top = 12
      Width = 40
      Height = 12
      Caption = 'N'#218'MERO'
    end
    object edtDDD: TDBEditNumero
      Left = 3
      Top = 24
      Width = 40
      Height = 23
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = -1
      ParentFont = False
      TabOrder = 0
      Mascara = True
      Alignment = taLeftJustify
      TipoMascara = tmGERAL
      NrDecimal = 2
      Decimais = False
      Negativo = False
      Tamanho = 3
    end
    object edtNumero: TDBEditFone
      Tag = 8
      Left = 47
      Top = 24
      Width = 100
      Height = 23
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      MaxLength = 9
      ParentFont = False
      TabOrder = 1
      Tamanho = 8
      Decimais = False
      Negativo = False
    end
  end
end
