inherited frmrelatoriorecebimentoslongoprazo: Tfrmrelatoriorecebimentoslongoprazo
  Left = 596
  Top = 295
  ActiveControl = edtDataInicial
  Caption = 'Relat'#243'rio de recebimentos a longo prazo'
  ClientHeight = 219
  ClientWidth = 515
  FormStyle = fsMDIChild
  Position = poOwnerFormCenter
  Visible = True
  PixelsPerInch = 96
  TextHeight = 13
  inherited pnlBarra: TPanel
    Width = 515
  end
  inherited pnlFundoJanela: TPanel
    Width = 515
    Height = 178
    object gbxEmpreendimento: TGroupBox
      Left = 5
      Top = 90
      Width = 502
      Height = 36
      Caption = 'EMPREENDIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      font.height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      inline fraConsultaEmprendimento: TfraConsultaCodigo
        Left = 2
        Top = 10
        Width = 498
        Height = 24
        HorzScrollBar.Range = 497
        VertScrollBar.Range = 23
        AutoScroll = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        inherited dtxDescricao: TtecDBText
          DataField = 'nome'
          DataSource = fraConsultaEmprendimento.dsrProcuraEmpreendimentos
        end
        inherited edfCodigo: TtecDBFindLookup
          DataField = 'codigo'
          DataSource = fraConsultaEmprendimento.dsrProcuraEmpreendimentos
          Group = 'Emp'
          MaxLength = 5
          OnFound = nil
          Operacao = opPESQUISA
          Parameter = 'Codigo'
          ActiveSetControls = False
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
        end
      end
    end
    object gbxCliente: TGroupBox
      Left = 5
      Top = 132
      Width = 502
      Height = 36
      Caption = 'CLIENTE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      font.height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      inline fraConsultaCliente: TfraConsultaCodigo
        Left = 2
        Top = 10
        Width = 498
        Height = 24
        HorzScrollBar.Range = 497
        VertScrollBar.Range = 23
        AutoScroll = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        inherited dtxDescricao: TtecDBText
          DataField = 'nome'
          DataSource = fraConsultaCliente.dsrProcuraCliente
        end
        inherited edfCodigo: TtecDBFindLookup
          DataField = 'codigo'
          DataSource = fraConsultaCliente.dsrProcuraCliente
          Group = 'Cliente'
          MaxLength = 8
          OnFound = nil
          Operacao = opPESQUISA
          Parameter = 'codigo'
          ActiveSetControls = False
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
        end
      end
    end
    object ckbResumo: TCheckBox
      Left = 316
      Top = 68
      Width = 191
      Height = 20
      Caption = 'Resumo por empreendimento'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      font.height = -12
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object gbxPeriodo: TGroupBox
      Left = 6
      Top = 48
      Width = 170
      Height = 36
      Caption = 'PER'#205'ODO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      font.height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object lblA: TLabel
        Left = 81
        Top = 14
        Width = 5
        Height = 12
        Caption = 'a'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
      end
      object edtDataInicial: TEditData
        Left = 2
        Top = 10
        Width = 75
        Height = 20
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 0
        Minimo = 37353
        Maximo = 10000
      end
      object edtDataFinal: TEditData
        Left = 92
        Top = 10
        Width = 75
        Height = 20
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 1
        Minimo = 37353
        Maximo = 65535
      end
    end
    object gbxdataBase: TGroupBox
      Left = 6
      Top = 6
      Width = 80
      Height = 36
      Caption = 'DATA BASE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      font.height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object edtDataBase: TEditData
        Left = 2
        Top = 10
        Width = 75
        Height = 20
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        font.height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 0
        Minimo = 37353
        Maximo = 0
      end
    end
  end
end
