inherited frmTrocarImoveisContrato: TfrmTrocarImoveisContrato
  Left = 471
  Top = 153
  Caption = 'Cadastro de Troca de Im'#243'veis no Contrato'
  ClientHeight = 416
  ClientWidth = 983
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlTopMenu: TPanel
    Width = 983
    inherited tblBarra: TToolBar
      Width = 758
      inherited sbnProcurar: TSpeedButton
        Visible = False
      end
    end
    inherited tblBarraCadastro: TToolBar
      inherited sbnIncluir: TSpeedButton
        Visible = False
      end
      inherited sbnExcluir: TSpeedButton
        Visible = False
      end
    end
  end
  object gbxDadosImovelaTrocar: TGroupBox
    Left = 8
    Top = 44
    Width = 481
    Height = 367
    Caption = 'IM'#211'VEL A TROCAR'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    object gbxEmpreendimentosaTrocar: TGroupBox
      Left = 10
      Top = 17
      Width = 465
      Height = 36
      Caption = 'EMPREENDIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object dtxCodigoEmpreendimento: TtecDBText
        Left = 4
        Top = 10
        Width = 77
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'codigoempreendimento'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
      object dtxDescricaoEmpreendimento: TtecDBText
        Left = 83
        Top = 10
        Width = 378
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'nome'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Alignment = taLeftJustify
      end
    end
    object gbxBlocosaTrocar: TGroupBox
      Left = 13
      Top = 57
      Width = 300
      Height = 36
      Caption = 'BLOCO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object dtxNomeBloco: TtecDBText
        Left = 4
        Top = 10
        Width = 293
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'nomebloco'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
    end
    object gbxNumeroaTrocar: TGroupBox
      Left = 328
      Top = 57
      Width = 147
      Height = 36
      Caption = 'N'#218'MERO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      object dtxNumero: TtecDBText
        Left = 4
        Top = 10
        Width = 140
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'numero'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taLeftJustify
      end
    end
    object gbxTipoUnidadeaTrocar: TGroupBox
      Left = 10
      Top = 185
      Width = 192
      Height = 36
      Caption = 'TIPO DE UNIDADE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      object dtxTipoUnidadeaTrocar: TtecDBText
        Left = 2
        Top = 10
        Width = 187
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'tipounidade'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taCenter
      end
    end
    object gbxPavimentoaTrocar: TGroupBox
      Left = 211
      Top = 185
      Width = 111
      Height = 36
      Caption = 'PAVIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      object dtxpavimentoaTrocar: TtecDBText
        Left = 2
        Top = 10
        Width = 105
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'pavimento'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taCenter
      end
    end
    object gbxareasaTrocar: TGroupBox
      Left = 10
      Top = 225
      Width = 417
      Height = 50
      Caption = #193'REAS'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
      object lblMais: TLabel
        Left = 97
        Top = 24
        Width = 13
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '+'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lblIgual: TLabel
        Left = 203
        Top = 24
        Width = 19
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '='
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        ParentFont = False
      end
      object gbxPrivativaaTrocar: TGroupBox
        Left = 5
        Top = 14
        Width = 90
        Height = 36
        Caption = 'PRIVATIVA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object dtxPrivativaaTrocar: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'areaprivativa'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxComumaTrocar: TGroupBox
        Left = 112
        Top = 14
        Width = 90
        Height = 36
        Caption = 'COMUM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object dtxComumaTrocar: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'areacomum'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxTotalaTrocar: TGroupBox
        Left = 222
        Top = 14
        Width = 90
        Height = 36
        Caption = 'TOTAL'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object dtxtotalaTrocar: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'AreaTotal'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxFracaoIdealaTrocar: TGroupBox
        Left = 323
        Top = 14
        Width = 90
        Height = 36
        Caption = 'FRA'#199#195'O IDEAL'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object dtxFracaoidealaTrocar: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'fracaoideal'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
    end
    object gbxObservacoesaTrocar: TGroupBox
      Left = 10
      Top = 281
      Width = 466
      Height = 81
      Caption = 'OBSERVA'#199#213'ES'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      object mmoObservacoesaTrocar: TtecDBMemo
        Left = 2
        Top = 14
        Width = 462
        Height = 65
        Align = alClient
        Color = clBtnFace
        DataField = 'observacoes'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
    object gbxPrecoVendaaTrocar: TGroupBox
      Left = 331
      Top = 178
      Width = 145
      Height = 49
      Caption = 'PRE'#199'O DE VENDA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      TabStop = True
      object edtPrecoVendaaTrocar: TDBEditNumero
        Left = 2
        Top = 10
        Width = 140
        Height = 36
        TabStop = False
        AutoSize = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        MaxLength = -1
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Text = 'edtPrecoVendaaTrocar'
        Mascara = True
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = True
        Negativo = False
        Tamanho = 9
        DataField = 'precovenda'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
      end
    end
    object gbxObsContratoaTrocar: TGroupBox
      Left = 13
      Top = 99
      Width = 463
      Height = 73
      Caption = 'OBSERVA'#199#213'ES DO EMPREENDIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 8
      object mmoObsContratoaTrocar: TtecDBMemo
        Left = 2
        Top = 14
        Width = 459
        Height = 57
        TabStop = False
        Align = alClient
        DataField = 'observacoesempreendimento'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentColor = True
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
  end
  object gbxDadosImovelTrocado: TGroupBox
    Left = 496
    Top = 44
    Width = 481
    Height = 367
    Caption = 'IM'#211'VEL TROCADO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Pitch = fpVariable
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    object gbxEmpreendimentosTrocado: TGroupBox
      Left = 10
      Top = 17
      Width = 465
      Height = 36
      Caption = 'EMPREENDIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      inline fraConsultaEmpreendimentoImovelTrocado: TfraConsultaCodigo
        Left = 2
        Top = 10
        Width = 460
        Height = 23
        HorzScrollBar.Range = 460
        VertScrollBar.Range = 23
        AutoScroll = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        inherited dtxDescricao: TtecDBText
          Width = 372
          DataField = 'nome'
          DataSource = fraConsultaEmpreendimentoImovelTrocado.dsrProcuraEmpreendimentos
        end
        inherited edfCodigo: TtecDBFindLookup
          DataField = 'codigoempreendimentotrocado'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Group = 'Empreendimentos'
          MaxLength = 6
          OnFound = nil
          LookupField = 'codigo'
          LookupSource = fraConsultaEmpreendimentoImovelTrocado.dsrProcuraEmpreendimentos
          Parameter = ' '
          ActiveSetControls = False
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
          LookupParameter = 'Codigo'
        end
      end
    end
    object gbxBlocosTrocado: TGroupBox
      Left = 13
      Top = 57
      Width = 300
      Height = 36
      Caption = 'BLOCO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      object clxBlocosTrocado: TTecDBLookupComboBox
        Left = 2
        Top = 10
        Width = 295
        Height = 23
        DataField = 'blocotrocado'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        KeyField = 'codigo'
        ListField = 'descricao'
        ListSource = dtmContratosImoveis.dsrConsultaBlocos
        ParentFont = False
        TabOrder = 0
        OnCloseUp = clxBlocosTrocadoCloseUp
        OnEnter = clxBlocosTrocadoEnter
        OnExit = clxBlocosTrocadoExit
      end
    end
    object gbxNumeroTrocado: TGroupBox
      Left = 328
      Top = 57
      Width = 147
      Height = 36
      Caption = 'N'#218'MERO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      object clxImoveisTrocado: TTecDBLookupComboBox
        Left = 2
        Top = 10
        Width = 142
        Height = 23
        DataField = 'numerotrocado'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        KeyField = 'imovel'
        ListField = 'imovel'
        ListSource = dtmContratosImoveis.dsrConsultaImoveis
        ParentFont = False
        TabOrder = 0
        OnCloseUp = clxImoveisaTrocarCloseUp
        OnEnter = clxImoveisTrocadoEnter
        OnExit = clxImoveisTrocadoExit
      end
    end
    object gbxTipoUnidadeTrocado: TGroupBox
      Left = 10
      Top = 185
      Width = 192
      Height = 36
      Caption = 'TIPO DE UNIDADE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      object dtxTipoUnidadeTrocada: TtecDBText
        Left = 2
        Top = 10
        Width = 187
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'tipounidadetrocado'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taCenter
      end
    end
    object GroupBox6: TGroupBox
      Left = 211
      Top = 185
      Width = 111
      Height = 36
      Caption = 'PAVIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      object gbxPavimentoTrocado: TtecDBText
        Left = 2
        Top = 10
        Width = 105
        Height = 23
        TabStop = False
        Color = clBtnFace
        DataField = 'pavimentotrocado'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Alignment = taCenter
      end
    end
    object gbxareasTrocada: TGroupBox
      Left = 10
      Top = 225
      Width = 417
      Height = 50
      Caption = #193'REAS'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
      object Label1: TLabel
        Left = 97
        Top = 24
        Width = 13
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '+'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label2: TLabel
        Left = 203
        Top = 24
        Width = 19
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '='
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        ParentFont = False
      end
      object gbxPrivativaTrocada: TGroupBox
        Left = 5
        Top = 14
        Width = 90
        Height = 36
        Caption = 'PRIVATIVA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object dtxPrivativaTrocado: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'areaprivativatrocado'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxComumTrocado: TGroupBox
        Left = 112
        Top = 14
        Width = 90
        Height = 36
        Caption = 'COMUM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object dtxComumTrocado: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'areacomumtrocado'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxTotalTrocado: TGroupBox
        Left = 222
        Top = 14
        Width = 90
        Height = 36
        Caption = 'TOTAL'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object dtxtotalTrocado: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'areatotaltrocado'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
      object gbxFracaoIdealTrocada: TGroupBox
        Left = 323
        Top = 14
        Width = 90
        Height = 36
        Caption = 'FRA'#199#195'O IDEAL'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object dtxFracaoidealTrocada: TtecDBText
          Left = 2
          Top = 10
          Width = 85
          Height = 23
          TabStop = False
          Color = clBtnFace
          DataField = 'fracaoidealtrocado'
          DataSource = dtmContratosImoveis.dsrImoveisVendidos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Alignment = taLeftJustify
        end
      end
    end
    object gbxObservacoesTrocada: TGroupBox
      Left = 10
      Top = 281
      Width = 466
      Height = 81
      Caption = 'OBSERVA'#199#213'ES'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      object mmoObservacoesTrocada: TtecDBMemo
        Left = 2
        Top = 14
        Width = 462
        Height = 65
        Align = alClient
        Color = clBtnFace
        DataField = 'observacoestrocado'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
    object gbxPrecoVendaTrocado: TGroupBox
      Left = 331
      Top = 179
      Width = 145
      Height = 49
      Caption = 'PRE'#199'O DE VENDA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'Helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      TabStop = True
      object edtPrecoVendaTrocado: TDBEditNumero
        Left = 2
        Top = 10
        Width = 140
        Height = 36
        TabStop = False
        AutoSize = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        MaxLength = -1
        ParentFont = False
        TabOrder = 0
        Text = 'edtPrecoVendaTrocado'
        Mascara = True
        TipoMascara = tmGERAL
        NrDecimal = 2
        Decimais = True
        Negativo = False
        Tamanho = 9
        DataField = 'precovenda'
        DataSource = dtmContratosImoveis.dsrImoveisVendidos
      end
    end
    object gbxObsContratoTrocado: TGroupBox
      Left = 13
      Top = 99
      Width = 463
      Height = 73
      Caption = 'OBSERVA'#199#213'ES DO EMPREENDIMENTO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      ParentFont = False
      TabOrder = 8
      object tecDBMemo2: TtecDBMemo
        Left = 2
        Top = 14
        Width = 459
        Height = 57
        TabStop = False
        Align = alClient
        DataField = 'observacoes'
        DataSource = fraConsultaEmpreendimentoImovelTrocado.dsrProcuraEmpreendimentos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentColor = True
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
  end
end
