[login]
filialbase=1
#banco=clamar_
#banco=homo2012_08_23

banco=maragna
porta=5434
#host=rot.frettalar.com.br
#host=200.180.4.80
#banco=eletrodelta
#host=187.55.208.102
#host=201.34.141.99
#host=201.34.141.99
#host=186.215.116.35

#krah_lá
#host=192.168.200.45
host=10.16.1.1

#banco=tecsoft
#host=krahice.no-ip.org

#host=187.55.208.102
#banco=agro
#gama
#host=187.52.178.148

#host=189.31.66.218 holding

#VALDIR
#host=201.47.57.59
 

#infotec
#host=186.215.116.178

#host=200.175.61.147
#host=200.146.120.227

usuario=sim
usuariopadrao=tecsoft
senhapadrao=filosofia
MaxColAutenticadora=48

[modulos]
atual=

disponiveis=vendas,adminsistema,estoque,caixa,contaspagar,cobranca,interlojas,entrega,montagens,livrosfiscais,financeiro,sac,bancos,contabil,producao,contasareceber
gdisponiveis=estoque

[impressoraetiqueta]
[impressoras]
fechamentocaixa=
notafiscal=
boleto=
contrato=

*[frentecaixa]
*trabalharcomo=sim
imprimircarneecf=0
carne=
imprimirlinefeednaimpressoramatricial=1
OSP=
SetupProcesso=
ControleProcesso=
notafiscalservicos=

[autenticacao]
autenticadora=1
autenticarecf=0
*[ecf]
*marca=Bematech
*controle=34363C624E450C83E819DA5198;0002;1
_#vd=32393B68433D
_data=26/06/2007
_vd=32313867488B75

*[ecf]
*marca=Bematech
*controle=34363C624E450C83E819DA5198;0002;1
[PCP]
DirExp=
[SPED]
DirSpedFiscal=N:\Clientes\Krah-ICE
DirSpedContabil=N:\Clientes\Criciuma\Contabil
[EXPORTAÇÃO]
DirExportação=N:\Gedovar\clientes\zita
[EXPORTAÇÃO PRODUTOS]
DirExportaçãoProdutos=N:\Clientes\Petipe\Exportacao\SaoJoao\Produtos
[EXPORTAÇÃO NOTAS TRANSFERENCIA]
DirExportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[IMPORTAÇÃO PRODUTOS]
DirImportaçãoProdutos=N:\Gedovar\expotimport
[IMPORTAÇÃO NOTAS TRANSFERENCIA]
DirImportaçãoNotasTransferencia=N:\Clientes\Petipe\Exportacao\SaoJoao\Notas
[MovimentacaoDiaria]
Movimentos=

[NFe]
Ambiente=2
TipoEmissao=1
DirEnvio=C:\Unimake\UniNFe\79863213000105\Envio
DirRetorno=C:\Unimake\UniNFe\79863213000105\Retorno
DirEnviados=C:\Unimake\UniNFe\79863213000105\Enviado\Autorizados
DirErros=C:\Unimake\UniNFe\79863213000105\Erro
DirComp=C:\Unimake\UniNFe\79863213000105\Compartilha
Visualizar=1
ExecNFe=C:\Unimake\UniNFe\uninfe.exe
ExecDANFE=C:\Unimake\UniNFe\unidanfe.exe
NumVias=1
Logotipo=N:\imagens\gama1.jpg


#[ecf]
#porta=3
#codigo=9
[Outros]
percentualdescontoetiqueta=0,00
PermissãoImpressãoProcessos=Sim
