inherited frmCadastroTabelaFretes: TfrmCadastroTabelaFretes
  Left = 677
  Top = 297
  Caption = 'Cadastro de Tabela de Fretes'
  ClientHeight = 243
  ClientWidth = 417
  FormStyle = fsMDIChild
  Visible = True
  PixelsPerInch = 96
  TextHeight = 16
  inherited pnlBarra: TPanel
    Width = 385
    Height = 39
  end
  inherited pnlTopMenu: TPanel
    Width = 417
    inherited tblBarra: TToolBar
      Width = 192
    end
  end
  object pnlfundojanela: TPanel
    Left = 0
    Top = 40
    Width = 417
    Height = 203
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 3
    TabOrder = 2
    object gbxTabeladeFretes: TGroupBox
      Left = 3
      Top = 3
      Width = 411
      Height = 197
      Align = alClient
      TabOrder = 0
      object gbxCodigo: TGroupBox
        Left = 10
        Top = 2
        Width = 60
        Height = 36
        Caption = 'C'#211'DIGO'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object edfCodigo: TtecDbEditFind
          Left = 2
          Top = 10
          Width = 55
          Height = 23
          DataField = 'codigo'
          DataSource = dtmCadastroTabelaFretes.dsrTabelaFrete
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          Group = 'TabelaFrete'
          MaxLength = 4
          Maximo = 0
          Minimo = 37353
          Adicional = 0
          Opcional = True
          ParentFont = False
          TabOrder = 0
          PermitirZero = False
          PermitirNulo = False
          Operacao = opATRIBUICAO
          Parameter = 'codigo'
          ActiveSetControls = True
          DenyInsert = True
          NoSetControls = <>
          SetControls = <>
        end
      end
      object gbxDescricao: TGroupBox
        Left = 78
        Top = 2
        Width = 300
        Height = 36
        Caption = 'DESCRI'#199#195'O'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object edtDescricao: TDBEditTexto
          Left = 2
          Top = 10
          Width = 295
          Height = 23
          DataField = 'descricao'
          DataSource = dtmCadastroTabelaFretes.dsrTabelaFrete
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          MaxLength = 12
          ParentFont = False
          TabOrder = 0
          CharCasenoDefault = False
        end
      end
      object gbxObservacoes: TGroupBox
        Left = 78
        Top = 105
        Width = 301
        Height = 73
        Caption = 'OBSERVA'#199#213'ES'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object mmoObservacoes: TtecDBMemo
          Left = 2
          Top = 14
          Width = 297
          Height = 57
          Align = alClient
          DataField = 'observacoes'
          DataSource = dtmCadastroTabelaFretes.dsrTabelaFrete
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
      end
      object gbxValores: TGroupBox
        Left = 79
        Top = 48
        Width = 219
        Height = 52
        Caption = 'VALORES PARA FRETE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 2
        object gbxValorFornecedor: TGroupBox
          Left = 112
          Top = 16
          Width = 100
          Height = 36
          Caption = 'FORNECEDOR'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          object edtValorFornecedor: TDBEditNumero
            Left = 2
            Top = 10
            Width = 95
            Height = 23
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -12
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            MaxLength = -1
            ParentFont = False
            TabOrder = 0
            Mascara = True
            Alignment = taLeftJustify
            TipoMascara = tmGERAL
            NrDecimal = 2
            Decimais = True
            Negativo = False
            Tamanho = 9
            DataField = 'valorfornecedor'
            DataSource = dtmCadastroTabelaFretes.dsrTabelaFrete
          end
        end
        object gbxValorCliente: TGroupBox
          Left = 6
          Top = 16
          Width = 100
          Height = 36
          Caption = 'CLIENTE'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'helvetica'
          Font.Pitch = fpVariable
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object edtValorCliente: TDBEditNumero
            Left = 2
            Top = 10
            Width = 95
            Height = 23
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -12
            Font.Name = 'helvetica'
            Font.Pitch = fpVariable
            Font.Style = []
            MaxLength = -1
            ParentFont = False
            TabOrder = 0
            Mascara = True
            Alignment = taLeftJustify
            TipoMascara = tmGERAL
            NrDecimal = 2
            Decimais = True
            Negativo = False
            Tamanho = 9
            DataField = 'valorcliente'
            DataSource = dtmCadastroTabelaFretes.dsrTabelaFrete
          end
        end
      end
    end
  end
end
