object fraEndereco: TfraEndereco
  Left = 0
  Top = 0
  Width = 459
  Height = 146
  Font.Color = clBlack
  Font.Height = 13
  Font.Name = 'helvetica'
  Font.Pitch = fpVariable
  Font.Style = []
  Font.Weight = 40
  ParentFont = False
  TabOrder = 0
  object gbxEndereco: TGroupBox
    Left = 0
    Top = 0
    Width = 459
    Height = 146
    Align = alClient
    Caption = 'ENDERE'#199'O'
    Font.Color = clBlack
    Font.Height = 9
    Font.Name = 'helvetica'
    Font.Pitch = fpVariable
    Font.Style = []
    Font.Weight = 40
    ParentFont = False
    TabOrder = 0
    object pnlNumero: TPanel
      Left = 2
      Top = 36
      Width = 455
      Height = 35
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 0
      object edtNumeroEndereco: TDBEditTexto
        Left = 1
        Top = 12
        Width = 80
        Height = 23
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        ParentFont = False
        TabOrder = 0
        CharCasenoDefault = False
      end
      object edtComplemento: TDBEditTexto
        Left = 83
        Top = 12
        Width = 338
        Height = 23
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        ParentFont = False
        TabOrder = 1
        CharCasenoDefault = False
      end
      object Label2: TLabel
        Left = 86
        Top = 0
        Width = 70
        Height = 12
        Alignment = taRightJustify
        Caption = 'COMPLEMENTO'
        Visible = False
      end
      object Label1: TLabel
        Left = 5
        Top = 0
        Width = 40
        Height = 12
        Alignment = taRightJustify
        Caption = 'N'#218'MERO'
        Visible = False
      end
    end
    object pnlBairro: TPanel
      Left = 2
      Top = 82
      Width = 455
      Height = 25
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 1
      object edtBairro: TtecDoubleDBEdit
        HelpType = htContext
        Left = 1
        Top = 0
        Width = 420
        Height = 23
        TabStop = False
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
      end
    end
    object pnlCidade: TPanel
      Left = 2
      Top = 119
      Width = 455
      Height = 23
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 2
      object edtCEP: TDBEditCep
        Left = 1
        Top = -1
        Width = 80
        Height = 23
        TabStop = False
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        MaxLength = 0
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Tamanho = 8
        Decimais = False
        Negativo = False
      end
      object edtCidade: TtecDoubleDBEdit
        HelpType = htContext
        Left = 84
        Top = -1
        Width = 305
        Height = 23
        TabStop = False
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        MaxLength = 30
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
      end
      object edtEstado: TDBEditTexto
        Left = 391
        Top = -1
        Width = 31
        Height = 23
        TabStop = False
        CharCase = ecUpperCase
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 12
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        MaxLength = 0
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        CharCasenoDefault = False
      end
    end
    object pnlRua: TPanel
      Left = 2
      Top = 12
      Width = 455
      Height = 24
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 3
      object mmoRua: TtecDBMemo
        Left = 0
        Top = 0
        Width = 421
        Height = 24
        Color = clNormalButton
        Font.Color = clBlack
        Font.Height = 11
        Font.Name = 'helvetica'
        Font.Pitch = fpVariable
        Font.Style = []
        Font.Weight = 40
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        TabOrder = 0
        TabStop = False
        WrapBreak = wbAnywhere
      end
    end
    object pnllblCidade: TPanel
      Left = 2
      Top = 107
      Width = 455
      Height = 12
      Align = alTop
      BevelOuter = bvNone
      Font.Color = clBlack
      Font.Height = 9
      Font.Name = 'helvetica'
      Font.Pitch = fpVariable
      Font.Style = []
      Font.Weight = 40
      ParentFont = False
      TabOrder = 4
      object lblCEP_: TLabel
        Left = 5
        Top = 2
        Width = 19
        Height = 12
        Alignment = taRightJustify
        Caption = 'CEP'
        Visible = False
      end
      object lblCidade_: TLabel
        Left = 86
        Top = 2
        Width = 36
        Height = 12
        Alignment = taRightJustify
        Caption = 'CIDADE'
        Visible = False
      end
      object lblUF_: TLabel
        Left = 393
        Top = 2
        Width = 13
        Height = 12
        Alignment = taRightJustify
        Caption = 'UF'
        Visible = False
      end
    end
    object pnllblBairro: TPanel
      Left = 2
      Top = 71
      Width = 455
      Height = 11
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 5
      object lblBairro_: TLabel
        Left = 6
        Top = 1
        Width = 36
        Height = 12
        Alignment = taRightJustify
        Caption = 'BAIRRO'
        Visible = False
      end
    end
  end
end
